In [52]:
import numpy as np
import pandas as pd
import requests
import lxml.html
import re
import urllib
from time import sleep
from prettytable import PrettyTable
from bs4 import BeautifulSoup

datafile = pd.read_csv("API_19_DS2_en_csv_v2_10515758.csv",sep = ',')

In [53]:
datafile

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,Urban population (% of total),SP.URB.TOTL.IN.ZS,50.776000,50.761000,50.746000,50.730000,50.715000,50.700000,...,4.342100e+01,4.305900e+01,4.294000e+01,4.295700e+01,4.299000e+01,4.304100e+01,4.310800e+01,43.192000,43.293000,NaN
1,Aruba,ABW,Urban population,SP.URB.TOTL,27526.000000,28141.000000,28532.000000,28761.000000,28924.000000,29082.000000,...,4.405200e+04,4.377800e+04,4.382200e+04,4.406400e+04,4.436000e+04,4.467400e+04,4.497900e+04,45275.000000,45572.000000,NaN
2,Aruba,ABW,Urban population growth (annual %),SP.URB.GROW,3.117931,2.209658,1.379868,0.799404,0.565140,0.544773,...,-7.305493e-01,-6.239346e-01,1.004566e-01,5.507148e-01,6.695040e-01,7.053514e-01,6.804037e-01,0.655929,0.653849,NaN
3,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.000000,55438.000000,56225.000000,56695.000000,57032.000000,57360.000000,...,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,104822.000000,105264.000000,NaN
4,Aruba,ABW,Population growth (annual %),SP.POP.GROW,3.148037,2.238144,1.409622,0.832453,0.592649,0.573468,...,9.861642e-02,2.126801e-01,3.769848e-01,5.121450e-01,5.929140e-01,5.874924e-01,5.246582e-01,0.459929,0.420781,NaN
5,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Aruba,ABW,"Prevalence of underweight, weight for age (% o...",SH.STA.MALN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aruba,ABW,"Community health workers (per 1,000 people)",SH.MED.CMHW.P3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Aruba,ABW,"Mortality rate, under-5 (per 1,000 live births)",SH.DYN.MORT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Aruba,ABW,"Primary completion rate, total (% of relevant ...",SE.PRM.CMPT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.624258e+01,9.478610e+01,NaN,NaN,9.657064e+01,1.011806e+02,NaN,NaN,NaN,NaN
10,Aruba,ABW,"School enrollment, primary and secondary (gros...",SE.ENR.PRSC.FM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.004440e+00,1.014600e+00,1.008710e+00,1.021560e+00,NaN,NaN,NaN,NaN,NaN,NaN
11,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.403979e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Aruba,ABW,CPIA public sector management and institutions...,IQ.CPA.PUBS.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Aruba,ABW,Ease of doing business index (1=most business-...,IC.BUS.EASE.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Aruba,ABW,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.527983,0.141163,NaN
15,Aruba,ABW,Marine protected areas (% of territorial waters),ER.MRN.PTMR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000105,NaN
16,Aruba,ABW,Terrestrial protected areas (% of total land a...,ER.LND.PTLD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.530000,18.917576,NaN
17,Aruba,ABW,"Annual freshwater withdrawals, total (% of int...",ER.H2O.FWTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Aruba,ABW,"Annual freshwater withdrawals, total (billion ...",ER.H2O.FWTL.K3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Aruba,ABW,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Aruba,ABW,Population living in areas where elevation is ...,EN.POP.EL5M.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.069167e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Aruba,ABW,Urban population living in areas where elevati...,EN.POP.EL5M.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.718044e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Aruba,ABW,Rural population living in areas where elevati...,EN.POP.EL5M.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.351123e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Aruba,ABW,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Aruba,ABW,GHG net emissions/removals by LUCF (Mt of CO2 ...,EN.CLC.GHGR.MT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Aruba,ABW,Disaster risk reduction progress score (1-5 sc...,EN.CLC.DRSK.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Aruba,ABW,SF6 gas emissions (thousand metric tons of CO2...,EN.ATM.SF6G.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Aruba,ABW,PFC gas emissions (thousand metric tons of CO2...,EN.ATM.PFCG.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Aruba,ABW,Nitrous oxide emissions (% change from 1990),EN.ATM.NOXE.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.821291e+01,-4.619562e+01,-4.565757e+01,-4.511953e+01,NaN,NaN,NaN,NaN,NaN,NaN
29,Aruba,ABW,Nitrous oxide emissions (thousand metric tons ...,EN.ATM.NOXE.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,6.123027e+00,6.361541e+00,6.425156e+00,6.488772e+00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20034,Zimbabwe,ZWE,CO2 emissions from gaseous fuel consumption (%...,EN.ATM.CO2E.GF.ZS,NaN,NaN,NaN,NaN,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
20035,Zimbabwe,ZWE,CO2 emissions from gaseous fuel consumption (kt),EN.ATM.CO2E.GF.KT,NaN,NaN,NaN,NaN,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
20036,Zimbabwe,ZWE,CO2 intensity (kg per kg of oil equivalent ene...,EN.ATM.CO2E.EG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.132464e-01,8.222593e-01,9.328746e-01,7.208452e-01,1.034544e+00,NaN,NaN,NaN,NaN,NaN
20037,Zimbabwe,ZWE,Energy use (kg of oil equivalent per capita),EG.USE.PCAP.KG.OE,NaN,NaN,NaN,NaN,NaN,NaN,...,6.615867e+02,6.714989e+02,7.125832e+02,7.348366e+02,7.496671e+02,NaN,NaN,NaN,NaN,NaN
20038,Zimbabwe,ZWE,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,5.310414e+02,5.468427e+02,5.702509e+02,5.427296e+02,5.575739e+02,5.369955e+02,NaN,NaN,NaN,NaN
20039,Zimbabwe,ZWE,"Energy use (kg of oil equivalent) per $1,000 G...",EG.USE.COMM.GD.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.466498e+02,3.863724e+02,3.667039e+02,3.314408e+02,3.392795e+02,NaN,NaN,NaN,NaN,NaN
20040,Zimbabwe,ZWE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.315371e+01,8.287954e+01,7.957423e+01,7.801970e+01,7.956109e+01,8.104929e+01,8.179781e+01,NaN,NaN,NaN
20041,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.817858e-01,1.084824e+00,1.421441e+00,1.825492e+00,1.734587e+00,1.436266e+00,1.328664e+00,NaN,NaN,NaN
20042,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,5.700000e+07,9.400000e+07,1.310000e+08,1.680000e+08,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN
20043,Zimbabwe,ZWE,Renewable electricity output (% of total elect...,EG.ELC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.564120e+01,6.800923e+01,5.785590e+01,6.039335e+01,5.393939e+01,5.560543e+01,5.272428e+01,NaN,NaN,NaN
20044,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.880263e-01,2.769763e-01,4.882812e-01,5.541671e-01,5.956113e-01,5.385996e-01,4.943867e-01,NaN,NaN,NaN
20045,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
20046,Zimbabwe,ZWE,Electricity production from natural gas source...,EG.ELC.NGAS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN
20047,Zimbabwe,ZWE,Electricity production from hydroelectric sour...,EG.ELC.HYRO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.485942e+01,6.692441e+01,5.643446e+01,5.856786e+01,5.220481e+01,5.416916e+01,5.139561e+01,NaN,NaN,NaN
20048,Zimbabwe,ZWE,Electricity production from coal sources (% of...,EG.ELC.COAL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.407077e+01,3.171379e+01,4.165582e+01,3.905248e+01,4.546499e+01,4.385597e+01,4.678134e+01,NaN,NaN,NaN
20049,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.336908e+01,3.606306e+01,3.690000e+01,3.672888e+01,3.707681e+01,3.230000e+01,3.370000e+01,38.145138,NaN,NaN
20050,Zimbabwe,ZWE,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.086305e+00,1.018022e+00,2.441511e+00,2.044131e+00,1.954060e+00,2.425173e+00,1.999687e+00,1.669274,1.121496,NaN
20051,Zimbabwe,ZWE,Cereal yield (kg per hectare),AG.YLD.CREL.KG,NaN,919.700000,905.900000,822.500000,820.500000,930.800000,...,4.523000e+02,7.337000e+02,5.876000e+02,6.960000e+02,6.697000e+02,8.363000e+02,5.586000e+02,580.000000,NaN,NaN
20052,Zimbabwe,ZWE,Average precipitation in depth (mm per year),AG.LND.PRCP.MM,NaN,NaN,657.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,6.570000e+02,NaN,6.570000e+02,NaN,NaN,NaN,NaN
20053,Zimbabwe,ZWE,Agricultural irrigated land (% of total agricu...,AG.LND.IRIG.AG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20054,Zimbabwe,ZWE,Forest area (% of land area),AG.LND.FRST.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.123304e+01,4.038775e+01,3.958020e+01,3.877265e+01,3.796510e+01,3.715756e+01,3.635001e+01,35.542457,NaN,NaN
20055,Zimbabwe,ZWE,Forest area (sq. km),AG.LND.FRST.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,1.595100e+05,1.562400e+05,1.531160e+05,1.499920e+05,1.468680e+05,1.437440e+05,1.406200e+05,137495.996100,NaN,NaN
20056,Zimbabwe,ZWE,Land area where elevation is below 5 meters (%...,AG.LND.EL5M.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20057,Zimbabwe,ZWE,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20058,Zimbabwe,ZWE,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20059,Zimbabwe,ZWE,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20060,Zimbabwe,ZWE,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20061,Zimbabwe,ZWE,Arable land (% of land area),AG.LND.ARBL.ZS,NaN,4.872690,5.001939,5.131188,5.260437,5.337986,...,1.059842e+01,1.033993e+01,1.085692e+01,1.033993e+01,1.033993e+01,1.033993e+01,1.033993e+01,10.339925,NaN,NaN
20062,Zimbabwe,ZWE,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,28.396019,28.615743,28.835466,29.055189,29.223213,...,4.213519e+01,4.187670e+01,4.239369e+01,4.187670e+01,4.187670e+01,4.187670e+01,4.187670e+01,41.876696,NaN,NaN
20063,Zimbabwe,ZWE,Agricultural land (sq. km),AG.LND.AGRI.K2,NaN,109850.000000,110700.000000,111550.000000,112400.000000,113050.000000,...,1.630000e+05,1.620000e+05,1.640000e+05,1.620000e+05,1.620000e+05,1.620000e+05,1.620000e+05,162000.000000,NaN,NaN

In [54]:
co2_emission = datafile[datafile['Indicator Code'] == 'EN.ATM.CO2E.KT']

In [55]:
co2_emission_2014 = co2_emission[['Country Name','2014']]

In [56]:
co2_emission_2014

                                            Country Name          2014
44                                                 Aruba  8.727460e+02
120                                          Afghanistan  9.809225e+03
196                                               Angola  3.476316e+04
272                                              Albania  5.716853e+03
348                                              Andorra  4.620420e+02
424                                           Arab World  1.895700e+06
500                                 United Arab Emirates  2.113695e+05
576                                            Argentina  2.040245e+05
652                                              Armenia  5.529836e+03
728                                       American Samoa           NaN
804                                  Antigua and Barbuda  5.317150e+02
880                                            Australia  3.612618e+05
956                                              Austria  5.871234e+04
1032                                          Azerbaijan  3.748774e+04
1108                                             Burundi  4.400400e+02
1184                                             Belgium  9.335082e+04
1260                                               Benin  6.318241e+03
1336                                        Burkina Faso  2.849259e+03
1412                                          Bangladesh  7.318965e+04
1488                                            Bulgaria  4.241619e+04
1564                                             Bahrain  3.133818e+04
1640                                        Bahamas, The  2.416553e+03
1716                              Bosnia and Herzegovina  2.223302e+04
1792                                             Belarus  6.349777e+04
1868                                              Belize  4.950450e+02
1944                                             Bermuda  5.757190e+02
2020                                             Bolivia  2.041052e+04
2096                                              Brazil  5.298082e+05
2172                                            Barbados  1.272449e+03
2248                                   Brunei Darussalam  9.108828e+03
...                                                  ...           ...
17828  Latin America & the Caribbean (IDA & IBRD coun...  1.844358e+06
17904                                        Timor-Leste  4.693760e+02
17980  Middle East & North Africa (IDA & IBRD countries)  1.415554e+06
18056                                              Tonga  1.210110e+02
18132                            South Asia (IDA & IBRD)  2.516435e+06
18208          Sub-Saharan Africa (IDA & IBRD countries)  8.228190e+05
18284                                Trinidad and Tobago  4.627387e+04
18360                                            Tunisia  2.882995e+04
18436                                             Turkey  3.459815e+05
18512                                             Tuvalu  1.100100e+01
18588                                           Tanzania  1.156205e+04
18664                                             Uganda  5.229142e+03
18740                                            Ukraine  2.272990e+05
18816                                Upper middle income  1.658879e+07
18892                                            Uruguay  6.747280e+03
18968                                      United States  5.254279e+06
19044                                         Uzbekistan  1.052136e+05
19120                     St. Vincent and the Grenadines  2.090190e+02
19196                                      Venezuela, RB  1.852202e+05
19272                             British Virgin Islands  1.796830e+02
19348                              Virgin Islands (U.S.)           NaN
19424                                            Vietnam  1.669108e+05
19500                                            Vanuatu  1.540140e+02
19576                                              World  3.613828e+07
19652                                              Samoa  1.980180e+02
19728                                             Kosovo           NaN
19804                                        Yemen, Rep.  2.269873e+04
19880                                       South Africa  4.897719e+05
19956                                             Zambia  4.503076e+03
20032                                           Zimbabwe  1.202043e+04

[264 rows x 2 columns]

In [15]:
co2_emission_2014.isnull().sum()

Country Name     0
2014            13
dtype: int64

In [57]:
population = datafile[datafile['Indicator Code'] == 'SP.POP.TOTL']

In [60]:
population_2014 = population[['Country Name','2014']]

In [61]:
population_2014

                                            Country Name          2014
3                                                  Aruba  1.037950e+05
79                                           Afghanistan  3.275802e+07
155                                               Angola  2.692047e+07
231                                              Albania  2.889104e+06
307                                              Andorra  7.922300e+04
383                                           Arab World  3.900430e+08
459                                 United Arab Emirates  9.070867e+06
535                                            Argentina  4.298152e+07
611                                              Armenia  2.906220e+06
687                                       American Samoa  5.543700e+04
763                                  Antigua and Barbuda  9.887500e+04
839                                            Australia  2.350414e+07
915                                              Austria  8.546356e+06
991                                           Azerbaijan  9.535079e+06
1067                                             Burundi  9.891790e+06
1143                                             Belgium  1.120906e+07
1219                                               Benin  1.028671e+07
1295                                        Burkina Faso  1.758598e+07
1371                                          Bangladesh  1.594053e+08
1447                                            Bulgaria  7.223938e+06
1523                                             Bahrain  1.336397e+06
1599                                        Bahamas, The  3.821690e+05
1675                              Bosnia and Herzegovina  3.566002e+06
1751                                             Belarus  9.474511e+06
1827                                              Belize  3.516940e+05
1903                                             Bermuda  6.513900e+04
1979                                             Bolivia  1.056216e+07
2055                                              Brazil  2.042131e+08
2131                                            Barbados  2.833850e+05
2207                                   Brunei Darussalam  4.117040e+05
...                                                  ...           ...
17787  Latin America & the Caribbean (IDA & IBRD coun...  6.081360e+08
17863                                        Timor-Leste  1.212814e+06
17939  Middle East & North Africa (IDA & IBRD countries)  3.567833e+08
18015                                              Tonga  1.057820e+05
18091                            South Asia (IDA & IBRD)  1.721848e+09
18167          Sub-Saharan Africa (IDA & IBRD countries)  9.790179e+08
18243                                Trinidad and Tobago  1.354493e+06
18319                                            Tunisia  1.114391e+07
18395                                             Turkey  7.703063e+07
18471                                             Tuvalu  1.090800e+04
18547                                           Tanzania  5.223487e+07
18623                                             Uganda  3.883334e+07
18699                                            Ukraine  4.527195e+07
18775                                Upper middle income  2.517980e+09
18851                                            Uruguay  3.419546e+06
18927                                      United States  3.186225e+08
19003                                         Uzbekistan  3.075770e+07
19079                     St. Vincent and the Grenadines  1.093570e+05
19155                                      Venezuela, RB  3.073838e+07
19231                             British Virgin Islands  2.958800e+04
19307                              Virgin Islands (U.S.)  1.078840e+05
19383                                            Vietnam  9.254492e+07
19459                                            Vanuatu  2.588500e+05
19535                                              World  7.271323e+09
19611                                              Samoa  1.922900e+05
19687                                             Kosovo  1.821800e+06
19763                                        Yemen, Rep.  2.624633e+07
19839                                       South Africa  5.453957e+07
19915                                             Zambia  1.562097e+07
19991                                           Zimbabwe  1.541168e+07

[264 rows x 2 columns]

In [65]:
co2_emission_2014.rename(columns={'2014':'2014_co2'})

                                            Country Name      2014_co2
44                                                 Aruba  8.727460e+02
120                                          Afghanistan  9.809225e+03
196                                               Angola  3.476316e+04
272                                              Albania  5.716853e+03
348                                              Andorra  4.620420e+02
424                                           Arab World  1.895700e+06
500                                 United Arab Emirates  2.113695e+05
576                                            Argentina  2.040245e+05
652                                              Armenia  5.529836e+03
728                                       American Samoa           NaN
804                                  Antigua and Barbuda  5.317150e+02
880                                            Australia  3.612618e+05
956                                              Austria  5.871234e+04
1032                                          Azerbaijan  3.748774e+04
1108                                             Burundi  4.400400e+02
1184                                             Belgium  9.335082e+04
1260                                               Benin  6.318241e+03
1336                                        Burkina Faso  2.849259e+03
1412                                          Bangladesh  7.318965e+04
1488                                            Bulgaria  4.241619e+04
1564                                             Bahrain  3.133818e+04
1640                                        Bahamas, The  2.416553e+03
1716                              Bosnia and Herzegovina  2.223302e+04
1792                                             Belarus  6.349777e+04
1868                                              Belize  4.950450e+02
1944                                             Bermuda  5.757190e+02
2020                                             Bolivia  2.041052e+04
2096                                              Brazil  5.298082e+05
2172                                            Barbados  1.272449e+03
2248                                   Brunei Darussalam  9.108828e+03
...                                                  ...           ...
17828  Latin America & the Caribbean (IDA & IBRD coun...  1.844358e+06
17904                                        Timor-Leste  4.693760e+02
17980  Middle East & North Africa (IDA & IBRD countries)  1.415554e+06
18056                                              Tonga  1.210110e+02
18132                            South Asia (IDA & IBRD)  2.516435e+06
18208          Sub-Saharan Africa (IDA & IBRD countries)  8.228190e+05
18284                                Trinidad and Tobago  4.627387e+04
18360                                            Tunisia  2.882995e+04
18436                                             Turkey  3.459815e+05
18512                                             Tuvalu  1.100100e+01
18588                                           Tanzania  1.156205e+04
18664                                             Uganda  5.229142e+03
18740                                            Ukraine  2.272990e+05
18816                                Upper middle income  1.658879e+07
18892                                            Uruguay  6.747280e+03
18968                                      United States  5.254279e+06
19044                                         Uzbekistan  1.052136e+05
19120                     St. Vincent and the Grenadines  2.090190e+02
19196                                      Venezuela, RB  1.852202e+05
19272                             British Virgin Islands  1.796830e+02
19348                              Virgin Islands (U.S.)           NaN
19424                                            Vietnam  1.669108e+05
19500                                            Vanuatu  1.540140e+02
19576                                              World  3.613828e+07
19652                                              Samoa  1.980180e+02
19728                                             Kosovo           NaN
19804                                        Yemen, Rep.  2.269873e+04
19880                                       South Africa  4.897719e+05
19956                                             Zambia  4.503076e+03
20032                                           Zimbabwe  1.202043e+04

[264 rows x 2 columns]

In [66]:
population_2014.rename(columns= {'2014': '2014_pop'})

                                            Country Name      2014_pop
3                                                  Aruba  1.037950e+05
79                                           Afghanistan  3.275802e+07
155                                               Angola  2.692047e+07
231                                              Albania  2.889104e+06
307                                              Andorra  7.922300e+04
383                                           Arab World  3.900430e+08
459                                 United Arab Emirates  9.070867e+06
535                                            Argentina  4.298152e+07
611                                              Armenia  2.906220e+06
687                                       American Samoa  5.543700e+04
763                                  Antigua and Barbuda  9.887500e+04
839                                            Australia  2.350414e+07
915                                              Austria  8.546356e+06
991                                           Azerbaijan  9.535079e+06
1067                                             Burundi  9.891790e+06
1143                                             Belgium  1.120906e+07
1219                                               Benin  1.028671e+07
1295                                        Burkina Faso  1.758598e+07
1371                                          Bangladesh  1.594053e+08
1447                                            Bulgaria  7.223938e+06
1523                                             Bahrain  1.336397e+06
1599                                        Bahamas, The  3.821690e+05
1675                              Bosnia and Herzegovina  3.566002e+06
1751                                             Belarus  9.474511e+06
1827                                              Belize  3.516940e+05
1903                                             Bermuda  6.513900e+04
1979                                             Bolivia  1.056216e+07
2055                                              Brazil  2.042131e+08
2131                                            Barbados  2.833850e+05
2207                                   Brunei Darussalam  4.117040e+05
...                                                  ...           ...
17787  Latin America & the Caribbean (IDA & IBRD coun...  6.081360e+08
17863                                        Timor-Leste  1.212814e+06
17939  Middle East & North Africa (IDA & IBRD countries)  3.567833e+08
18015                                              Tonga  1.057820e+05
18091                            South Asia (IDA & IBRD)  1.721848e+09
18167          Sub-Saharan Africa (IDA & IBRD countries)  9.790179e+08
18243                                Trinidad and Tobago  1.354493e+06
18319                                            Tunisia  1.114391e+07
18395                                             Turkey  7.703063e+07
18471                                             Tuvalu  1.090800e+04
18547                                           Tanzania  5.223487e+07
18623                                             Uganda  3.883334e+07
18699                                            Ukraine  4.527195e+07
18775                                Upper middle income  2.517980e+09
18851                                            Uruguay  3.419546e+06
18927                                      United States  3.186225e+08
19003                                         Uzbekistan  3.075770e+07
19079                     St. Vincent and the Grenadines  1.093570e+05
19155                                      Venezuela, RB  3.073838e+07
19231                             British Virgin Islands  2.958800e+04
19307                              Virgin Islands (U.S.)  1.078840e+05
19383                                            Vietnam  9.254492e+07
19459                                            Vanuatu  2.588500e+05
19535                                              World  7.271323e+09
19611                                              Samoa  1.922900e+05
19687                                             Kosovo  1.821800e+06
19763                                        Yemen, Rep.  2.624633e+07
19839                                       South Africa  5.453957e+07
19915                                             Zambia  1.562097e+07
19991                                           Zimbabwe  1.541168e+07

[264 rows x 2 columns]

In [127]:
co2_per_capitadf = pd.merge(co2_emission_2014, population_2014, on = 'Country Name')

In [128]:
co2_per_capitadf

,Country Name,2014_x,2014_y
0,Aruba,8.727460e+02,1.037950e+05
1,Afghanistan,9.809225e+03,3.275802e+07
2,Angola,3.476316e+04,2.692047e+07
3,Albania,5.716853e+03,2.889104e+06
4,Andorra,4.620420e+02,7.922300e+04
5,Arab World,1.895700e+06,3.900430e+08
6,United Arab Emirates,2.113695e+05,9.070867e+06
7,Argentina,2.040245e+05,4.298152e+07
8,Armenia,5.529836e+03,2.906220e+06
9,American Samoa,NaN,5.543700e+04
10,Antigua and Barbuda,5.317150e+02,9.887500e+04
11,Australia,3.612618e+05,2.350414e+07
12,Austria,5.871234e+04,8.546356e+06
13,Azerbaijan,3.748774e+04,9.535079e+06
14,Burundi,4.400400e+02,9.891790e+06
15,Belgium,9.335082e+04,1.120906e+07
16,Benin,6.318241e+03,1.028671e+07
17,Burkina Faso,2.849259e+03,1.758598e+07
18,Bangladesh,7.318965e+04,1.594053e+08
19,Bulgaria,4.241619e+04,7.223938e+06
20,Bahrain,3.133818e+04,1.336397e+06
21,"Bahamas, The",2.416553e+03,3.821690e+05
22,Bosnia and Herzegovina,2.223302e+04,3.566002e+06
23,Belarus,6.349777e+04,9.474511e+06
24,Belize,4.950450e+02,3.516940e+05
25,Bermuda,5.757190e+02,6.513900e+04
26,Bolivia,2.041052e+04,1.056216e+07
27,Brazil,5.298082e+05,2.042131e+08
28,Barbados,1.272449e+03,2.833850e+05
29,Brunei Darussalam,9.108828e+03,4.117040e+05
...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,1.844358e+06,6.081360e+08
235,Timor-Leste,4.693760e+02,1.212814e+06
236,Middle East & North Africa (IDA & IBRD countries),1.415554e+06,3.567833e+08
237,Tonga,1.210110e+02,1.057820e+05
238,South Asia (IDA & IBRD),2.516435e+06,1.721848e+09
239,Sub-Saharan Africa (IDA & IBRD countries),8.228190e+05,9.790179e+08
240,Trinidad and Tobago,4.627387e+04,1.354493e+06
241,Tunisia,2.882995e+04,1.114391e+07
242,Turkey,3.459815e+05,7.703063e+07
243,Tuvalu,1.100100e+01,1.090800e+04
244,Tanzania,1.156205e+04,5.223487e+07
245,Uganda,5.229142e+03,3.883334e+07
246,Ukraine,2.272990e+05,4.527195e+07
247,Upper middle income,1.658879e+07,2.517980e+09
248,Uruguay,6.747280e+03,3.419546e+06
249,United States,5.254279e+06,3.186225e+08
250,Uzbekistan,1.052136e+05,3.075770e+07
251,St. Vincent and the Grenadines,2.090190e+02,1.093570e+05
252,"Venezuela, RB",1.852202e+05,3.073838e+07
253,British Virgin Islands,1.796830e+02,2.958800e+04
254,Virgin Islands (U.S.),NaN,1.078840e+05
255,Vietnam,1.669108e+05,9.254492e+07
256,Vanuatu,1.540140e+02,2.588500e+05
257,World,3.613828e+07,7.271323e+09
258,Samoa,1.980180e+02,1.922900e+05
259,Kosovo,NaN,1.821800e+06
260,"Yemen, Rep.",2.269873e+04,2.624633e+07
261,South Africa,4.897719e+05,5.453957e+07
262,Zambia,4.503076e+03,1.562097e+07
263,Zimbabwe,1.202043e+04,1.541168e+07

In [72]:
per_capita_co2_em = co2_per_capitadf['2014_x']/co2_per_capitadf['2014_y']

In [136]:
co2_per_capitadf['co2_per_capita'] = per_capita_co2_em

In [137]:
co2_per_capitadf.dropna()

,Country Name,2014_x,2014_y,co2_per_capita
0,Aruba,8.727460e+02,1.037950e+05,0.008408
1,Afghanistan,9.809225e+03,3.275802e+07,0.000299
2,Angola,3.476316e+04,2.692047e+07,0.001291
3,Albania,5.716853e+03,2.889104e+06,0.001979
4,Andorra,4.620420e+02,7.922300e+04,0.005832
5,Arab World,1.895700e+06,3.900430e+08,0.004860
6,United Arab Emirates,2.113695e+05,9.070867e+06,0.023302
7,Argentina,2.040245e+05,4.298152e+07,0.004747
8,Armenia,5.529836e+03,2.906220e+06,0.001903
10,Antigua and Barbuda,5.317150e+02,9.887500e+04,0.005378
11,Australia,3.612618e+05,2.350414e+07,0.015370
12,Austria,5.871234e+04,8.546356e+06,0.006870
13,Azerbaijan,3.748774e+04,9.535079e+06,0.003932
14,Burundi,4.400400e+02,9.891790e+06,0.000044
15,Belgium,9.335082e+04,1.120906e+07,0.008328
16,Benin,6.318241e+03,1.028671e+07,0.000614
17,Burkina Faso,2.849259e+03,1.758598e+07,0.000162
18,Bangladesh,7.318965e+04,1.594053e+08,0.000459
19,Bulgaria,4.241619e+04,7.223938e+06,0.005872
20,Bahrain,3.133818e+04,1.336397e+06,0.023450
21,"Bahamas, The",2.416553e+03,3.821690e+05,0.006323
22,Bosnia and Herzegovina,2.223302e+04,3.566002e+06,0.006235
23,Belarus,6.349777e+04,9.474511e+06,0.006702
24,Belize,4.950450e+02,3.516940e+05,0.001408
25,Bermuda,5.757190e+02,6.513900e+04,0.008838
26,Bolivia,2.041052e+04,1.056216e+07,0.001932
27,Brazil,5.298082e+05,2.042131e+08,0.002594
28,Barbados,1.272449e+03,2.833850e+05,0.004490
29,Brunei Darussalam,9.108828e+03,4.117040e+05,0.022125
30,Bhutan,1.001091e+03,7.764480e+05,0.001289
...,...,...,...,...
232,Tajikistan,5.188805e+03,8.362745e+06,0.000620
233,Turkmenistan,6.842255e+04,5.466241e+06,0.012517
234,Latin America & the Caribbean (IDA & IBRD coun...,1.844358e+06,6.081360e+08,0.003033
235,Timor-Leste,4.693760e+02,1.212814e+06,0.000387
236,Middle East & North Africa (IDA & IBRD countries),1.415554e+06,3.567833e+08,0.003968
237,Tonga,1.210110e+02,1.057820e+05,0.001144
238,South Asia (IDA & IBRD),2.516435e+06,1.721848e+09,0.001461
239,Sub-Saharan Africa (IDA & IBRD countries),8.228190e+05,9.790179e+08,0.000840
240,Trinidad and Tobago,4.627387e+04,1.354493e+06,0.034163
241,Tunisia,2.882995e+04,1.114391e+07,0.002587
242,Turkey,3.459815e+05,7.703063e+07,0.004491
243,Tuvalu,1.100100e+01,1.090800e+04,0.001009
244,Tanzania,1.156205e+04,5.223487e+07,0.000221
245,Uganda,5.229142e+03,3.883334e+07,0.000135
246,Ukraine,2.272990e+05,4.527195e+07,0.005021
247,Upper middle income,1.658879e+07,2.517980e+09,0.006588
248,Uruguay,6.747280e+03,3.419546e+06,0.001973
249,United States,5.254279e+06,3.186225e+08,0.016491
250,Uzbekistan,1.052136e+05,3.075770e+07,0.003421
251,St. Vincent and the Grenadines,2.090190e+02,1.093570e+05,0.001911
252,"Venezuela, RB",1.852202e+05,3.073838e+07,0.006026
253,British Virgin Islands,1.796830e+02,2.958800e+04,0.006073
255,Vietnam,1.669108e+05,9.254492e+07,0.001804
256,Vanuatu,1.540140e+02,2.588500e+05,0.000595
257,World,3.613828e+07,7.271323e+09,0.004970
258,Samoa,1.980180e+02,1.922900e+05,0.001030
260,"Yemen, Rep.",2.269873e+04,2.624633e+07,0.000865
261,South Africa,4.897719e+05,5.453957e+07,0.008980
262,Zambia,4.503076e+03,1.562097e+07,0.000288
263,Zimbabwe,1.202043e+04,1.541168e+07,0.000780

In [80]:
developed_url = 'http://worldpopulationreview.com/countries/developed-countries/'

In [87]:
r = requests.get(developed_url)
tree = lxml.html.fromstring(r.content)

In [102]:
tree

In [153]:
developed_country = tree.xpath('//li/a/text()')

In [154]:
developed_country = developed_country[8:]

In [160]:
len(developed_country)

31

In [155]:
developed_country

['Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Iceland',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Luxembourg',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Portugal',
 'Slovenia',
 'South Korea',
 'Spain',
 'Sweden',
 'Singapore',
 'Switzerland',
 'Turkey',
 'United Kingdom',
 'United States']

In [95]:
developing_url = 'https://isge2018.isgesociety.com/registration/list-of-developing-countries/'

In [96]:
r2 = requests.get(developing_url)
tree2 = lxml.html.fromstring(r2.content)

In [101]:
tree2

In [103]:
developing_country = tree2.xpath('//div/ul/li/text()')

In [118]:
developing_country = developing_country[4:]

In [199]:
developing_country

['Afghanistan ',
 'Albania ',
 'Algeria ',
 'American Samoa ',
 'Angola ',
 'Antigua and Barbuda ',
 'Argentina ',
 'Armenia ',
 'Azerbaijan ',
 'Bangladesh ',
 'Belarus ',
 'Belize  ',
 'Benin ',
 'Bhutan ',
 'Bolivia ',
 'Bosnia and Herzegovina ',
 'Botswana ',
 'Brazil ',
 'Bulgaria ',
 'Burkina Faso ',
 'Burundi ',
 'Cambodia ',
 'Cameroon ',
 'Cape Verde ',
 'Central African Republic ',
 'Chad ',
 'Chile ',
 'China ',
 'Colombia ',
 'Comoros ',
 'Congo, Dem. Rep ',
 'Congo, Rep. ',
 'Costa Rica ',
 'Côte d’Ivoire ',
 'Cuba ',
 'Djibouti ',
 'Dominica ',
 'Dominican Republic  ',
 'Ecuador ',
 'Egypt, Arab Rep. ',
 'El Salvador ',
 'Eritrea ',
 'Ethiopia ',
 'Fiji ',
 'Gabon ',
 'Gambia ',
 'Georgia ',
 'Ghana ',
 'Grenada ',
 'Guatemala ',
 'Guinea ',
 'Guinea-Bisau ',
 'Guyana ',
 'Haiti ',
 'Honduras ',
 'India ',
 'Indonesia ',
 'Iran, Islamic Rep. ',
 'Iraq ',
 'Jamaica ',
 'Jordan ',
 'Kazakhstan ',
 'Kenya ',
 'Kiribati ',
 'Korea, Dem Rep. ',
 'Kosovo  ',
 'Kyrgyz Republic ',
 'Lao PDR ',
 'Latvia ',
 'Lebanon ',
 'Lesotho ',
 'Liberia ',
 'Libya ',
 'Lithuania ',
 'Macedonia, FYR  ',
 'Madagascar ',
 'Malawi ',
 'Malaysia ',
 'Maldives ',
 'Mali ',
 'Marshall Islands ',
 'Mauritania ',
 'Mauritius ',
 'Mayotte ',
 'Mexico ',
 'Micronesia, Fed. Sts. ',
 'Moldova ',
 'Mongolia ',
 'Montenegro ',
 'Morocco ',
 'Mozambique ',
 'Myanmar ',
 'Namibia ',
 'Nepal ',
 'Nicaragua ',
 'Niger ',
 'Nigeria  ',
 'Pakistan  ',
 'Palau ',
 'Panama ',
 'Papua New Guinea  ',
 'Paraguay ',
 'Peru  ',
 'Philippines ',
 'Romania ',
 'Russian Federation ',
 'Rwanda ',
 'Samoa ',
 'São Tomé and Principe ',
 'Senegal ',
 'Serbia ',
 'Seychelles ',
 'Sierra Leone ',
 'Solomon Islands ',
 'Somalia ',
 'South Africa ',
 'Sri Lanka ',
 'St. Kitts and Nevis ',
 'St. Lucia ',
 'St. Vincent and the Grenadines ',
 'Sudan ',
 'Suriname ',
 'Swaziland ',
 'Syrian Arab Republic ',
 'Tajikistan ',
 'Tanzania ',
 'Thailand ',
 'Timor-Leste ',
 'Togo ',
 'Tonga ',
 'Tunisia ',
 'Turkey ',
 'Turkmenistan ',
 'Tuvalu ',
 'Uganda ',
 'Ukraine ',
 'Uruguay ',
 'Uzbekistan ',
 'Vanuatu ',
 'Venezuela',
 'Vietnam ',
 'West Bank and Gaza ',
 'Yemen, Rep. ',
 'Zambia ',
 'Zimbabwe ']

In [156]:
developed_country_co2 = co2_per_capitadf[co2_per_capitadf['Country Name'].isin(developed_country)]

In [334]:
developed_country_co2['co2_per_thousand'] = developed_country_co2['co2_per_capita'] * 1000000

/Users/sgarygao/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [335]:
developed_country_co2

,Country Name,2014_x,2014_y,co2_per_capita,co2_per_thousand
11,Australia,361261.839,23504138.0,0.015370,15370.137760
12,Austria,58712.337,8546356.0,0.006870,6869.867930
15,Belgium,93350.819,11209057.0,0.008328,8328.159898
33,Canada,537193.498,35535348.0,0.015117,15117.158779
35,Switzerland,35305.876,8188649.0,0.004312,4311.562994
51,Cyprus,6061.551,1152309.0,0.005260,5260.352041
52,Czech Republic,96475.103,10525347.0,0.009166,9165.978376
53,Germany,719883.438,80982500.0,0.008889,8889.370395
56,Denmark,33498.045,5643475.0,0.005936,5935.712482
68,Spain,233976.602,46480882.0,0.005034,5033.824487
69,Estonia,19519.441,1314545.0,0.014849,14848.819173
73,Finland,47300.633,5461512.0,0.008661,8660.721243
75,France,303275.568,66316092.0,0.004573,4573.182147
79,United Kingdom,419820.162,64613160.0,0.006497,6497.440490
87,Greece,67318.786,10892413.0,0.006180,6180.337268
109,Ireland,34066.430,4657740.0,0.007314,7313.939808
112,Iceland,1983.847,327386.0,0.006060,6059.657407
113,Israel,64601.539,8215700.0,0.007863,7863.181348
114,Italy,320411.459,60789140.0,0.005271,5270.866786
117,Japan,1214048.358,127276000.0,0.009539,9538.706103
142,Luxembourg,9658.878,556319.0,0.017362,17362.121373
174,Netherlands,167303.208,16865008.0,0.009920,9920.138075
175,Norway,47626.996,5137232.0,0.009271,9270.945132
178,New Zealand,34664.151,4509700.0,0.007687,7686.575825
192,Portugal,45052.762,10401062.0,0.004332,4331.554028
206,Singapore,56372.791,5469724.0,0.010306,10306.331910
220,Slovenia,12812.498,2061980.0,0.006214,6213.686845
221,Sweden,43420.947,9696110.0,0.004478,4478.182178
242,Turkey,345981.450,77030628.0,0.004491,4491.479026
249,United States,5254279.285,318622525.0,0.016491,16490.608393

In [336]:
sum(developed_country_co2['co2_per_thousand'])

251640.5997018714

In [337]:
max(developed_country_co2['co2_per_thousand'])

17362.121372809484

In [338]:
min(developed_country_co2['co2_per_thousand'])

4311.562994090968

In [346]:
developed_max = developed_country_co2[developed_country_co2['co2_per_thousand'] == max(developed_country_co2['co2_per_thousand'])]

In [347]:
developed_min = developed_country_co2[developed_country_co2['co2_per_thousand'] == min(developed_country_co2['co2_per_thousand'])]

In [356]:
developed_outcome = developed_max.append(developed_min)

In [352]:
developing_country_co2['co2_per_thousand'] = developing_country_co2['co2_per_capita'] * 1000000

/Users/sgarygao/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [353]:
developing_country_co2

,Country Name,2014_x,2014_y,co2_per_capita,co2_per_thousand
1,Afghanistan,9.809225e+03,3.275802e+07,0.000299,299.444991
2,Angola,3.476316e+04,2.692047e+07,0.001291,1291.328315
3,Albania,5.716853e+03,2.889104e+06,0.001979,1978.763312
7,Argentina,2.040245e+05,4.298152e+07,0.004747,4746.797455
8,Armenia,5.529836e+03,2.906220e+06,0.001903,1902.758910
9,American Samoa,NaN,5.543700e+04,NaN,NaN
10,Antigua and Barbuda,5.317150e+02,9.887500e+04,0.005378,5377.648546
13,Azerbaijan,3.748774e+04,9.535079e+06,0.003932,3931.560609
14,Burundi,4.400400e+02,9.891790e+06,0.000044,44.485376
16,Benin,6.318241e+03,1.028671e+07,0.000614,614.213852
17,Burkina Faso,2.849259e+03,1.758598e+07,0.000162,162.018806
18,Bangladesh,7.318965e+04,1.594053e+08,0.000459,459.141965
19,Bulgaria,4.241619e+04,7.223938e+06,0.005872,5871.615869
22,Bosnia and Herzegovina,2.223302e+04,3.566002e+06,0.006235,6234.719162
23,Belarus,6.349777e+04,9.474511e+06,0.006702,6701.957705
26,Bolivia,2.041052e+04,1.056216e+07,0.001932,1932.419499
27,Brazil,5.298082e+05,2.042131e+08,0.002594,2594.388285
30,Bhutan,1.001091e+03,7.764480e+05,0.001289,1289.321371
31,Botswana,7.033306e+03,2.168573e+06,0.003243,3243.287637
32,Central African Republic,3.006940e+02,4.515392e+06,0.000067,66.593111
37,Chile,8.256251e+04,1.761380e+07,0.004687,4687.376624
38,China,1.029193e+07,1.364270e+09,0.007544,7543.907643
40,Cameroon,7.003970e+03,2.223990e+07,0.000315,314.928068
42,"Congo, Rep.",3.094948e+03,4.871101e+06,0.000635,635.369293
43,Colombia,8.409164e+04,4.779191e+07,0.001760,1759.537174
44,Comoros,1.540140e+02,7.593850e+05,0.000203,202.814119
46,Costa Rica,7.759372e+03,4.757575e+06,0.001631,1630.951062
48,Cuba,3.483650e+04,1.143977e+07,0.003045,3045.210624
54,Djibouti,7.223990e+02,9.121640e+05,0.000792,791.961752
55,Dominica,1.356790e+02,7.277800e+04,0.001864,1864.285911
...,...,...,...,...,...
208,Sierra Leone,1.309119e+03,7.079162e+06,0.000185,184.925702
209,El Salvador,6.285238e+03,6.281189e+06,0.001001,1000.644623
211,Somalia,6.087220e+02,1.351312e+07,0.000045,45.046723
212,Serbia,3.766742e+04,7.130576e+06,0.005283,5282.521917
218,Suriname,1.991181e+03,5.479280e+05,0.003634,3634.019433
224,Seychelles,4.950450e+02,9.135900e+04,0.005419,5418.677963
225,Syrian Arab Republic,3.070379e+04,1.920309e+07,0.001599,1598.898459
227,Chad,7.297330e+02,1.356944e+07,0.000054,53.777688
230,Togo,2.621905e+03,7.228915e+06,0.000363,362.696892
231,Thailand,3.162127e+05,6.841677e+07,0.004622,4621.860032
232,Tajikistan,5.188805e+03,8.362745e+06,0.000620,620.466725
233,Turkmenistan,6.842255e+04,5.466241e+06,0.012517,12517.295341
235,Timor-Leste,4.693760e+02,1.212814e+06,0.000387,387.014002
237,Tonga,1.210110e+02,1.057820e+05,0.001144,1143.965892
241,Tunisia,2.882995e+04,1.114391e+07,0.002587,2587.059584
242,Turkey,3.459815e+05,7.703063e+07,0.004491,4491.479026
243,Tuvalu,1.100100e+01,1.090800e+04,0.001009,1008.525853
244,Tanzania,1.156205e+04,5.223487e+07,0.000221,221.347372
245,Uganda,5.229142e+03,3.883334e+07,0.000135,134.656001
246,Ukraine,2.272990e+05,4.527195e+07,0.005021,5020.747064
248,Uruguay,6.747280e+03,3.419546e+06,0.001973,1973.150822
250,Uzbekistan,1.052136e+05,3.075770e+07,0.003421,3420.722746
251,St. Vincent and the Grenadines,2.090190e+02,1.093570e+05,0.001911,1911.345410
255,Vietnam,1.669108e+05,9.254492e+07,0.001804,1803.565750
256,Vanuatu,1.540140e+02,2.588500e+05,0.000595,594.993239
258,Samoa,1.980180e+02,1.922900e+05,0.001030,1029.788341
260,"Yemen, Rep.",2.269873e+04,2.624633e+07,0.000865,864.834535
261,South Africa,4.897719e+05,5.453957e+07,0.008980,8980.119297
262,Zambia,4.503076e+03,1.562097e+07,0.000288,288.271141
263,Zimbabwe,1.202043e+04,1.541168e+07,0.000780,779.955845

In [354]:
developing_max = developing_country_co2[developing_country_co2['co2_per_thousand'] == max(developing_country_co2['co2_per_thousand'])]

In [355]:
developing_min = developing_country_co2[developing_country_co2['co2_per_thousand'] == min(developing_country_co2['co2_per_thousand'])]

In [357]:
developing_outcome = developing_max.append(developing_min)

In [360]:
outcome1 = developing_outcome.append(developed_outcome)

In [362]:
outcome1.rename(columns= {'2014_x':'2014_co2_emission','2014_y':'2014_pop'})

,Country Name,2014_co2_emission,2014_pop,co2_per_capita,co2_per_thousand
118,Kazakhstan,248314.572,17288285.0,0.014363,14363.169742
14,Burundi,440.040,9891790.0,0.000044,44.485376
142,Luxembourg,9658.878,556319.0,0.017362,17362.121373
35,Switzerland,35305.876,8188649.0,0.004312,4311.562994

In [172]:
developed_country_co2['Country Name']

11          Australia
12            Austria
15            Belgium
33             Canada
35        Switzerland
51             Cyprus
52     Czech Republic
53            Germany
56            Denmark
68              Spain
69            Estonia
73            Finland
75             France
79     United Kingdom
87             Greece
109           Ireland
112           Iceland
113            Israel
114             Italy
117             Japan
142        Luxembourg
174       Netherlands
175            Norway
178       New Zealand
192          Portugal
206         Singapore
220          Slovenia
221            Sweden
242            Turkey
249     United States
Name: Country Name, dtype: object

In [164]:
len(developed_country_co2)

30

In [176]:
len(developed_country)

31

In [190]:
developed_country_co2_list =  list(developed_country_co2['Country Name'])

In [192]:
developed_country_co2_list

['Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Switzerland',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Denmark',
 'Spain',
 'Estonia',
 'Finland',
 'France',
 'United Kingdom',
 'Greece',
 'Ireland',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Luxembourg',
 'Netherlands',
 'Norway',
 'New Zealand',
 'Portugal',
 'Singapore',
 'Slovenia',
 'Sweden',
 'Turkey',
 'United States']

In [193]:
for i in range(0,30):
    if developed_country[i] not in developed_country_co2_list:
        missing_country = developed_country[i]

In [194]:
missing_country

'South Korea'

In [177]:
co2_per_capitadf[co2_per_capitadf['Country Name'] == 'South Korea']

Empty DataFrame
Columns: [Country Name, 2014_x, 2014_y, co2_per_capita]
Index: []

In [200]:
developing_country

['Afghanistan ',
 'Albania ',
 'Algeria ',
 'American Samoa ',
 'Angola ',
 'Antigua and Barbuda ',
 'Argentina ',
 'Armenia ',
 'Azerbaijan ',
 'Bangladesh ',
 'Belarus ',
 'Belize  ',
 'Benin ',
 'Bhutan ',
 'Bolivia ',
 'Bosnia and Herzegovina ',
 'Botswana ',
 'Brazil ',
 'Bulgaria ',
 'Burkina Faso ',
 'Burundi ',
 'Cambodia ',
 'Cameroon ',
 'Cape Verde ',
 'Central African Republic ',
 'Chad ',
 'Chile ',
 'China ',
 'Colombia ',
 'Comoros ',
 'Congo, Dem. Rep ',
 'Congo, Rep. ',
 'Costa Rica ',
 'Côte d’Ivoire ',
 'Cuba ',
 'Djibouti ',
 'Dominica ',
 'Dominican Republic  ',
 'Ecuador ',
 'Egypt, Arab Rep. ',
 'El Salvador ',
 'Eritrea ',
 'Ethiopia ',
 'Fiji ',
 'Gabon ',
 'Gambia ',
 'Georgia ',
 'Ghana ',
 'Grenada ',
 'Guatemala ',
 'Guinea ',
 'Guinea-Bisau ',
 'Guyana ',
 'Haiti ',
 'Honduras ',
 'India ',
 'Indonesia ',
 'Iran, Islamic Rep. ',
 'Iraq ',
 'Jamaica ',
 'Jordan ',
 'Kazakhstan ',
 'Kenya ',
 'Kiribati ',
 'Korea, Dem Rep. ',
 'Kosovo  ',
 'Kyrgyz Republic ',
 'Lao PDR ',
 'Latvia ',
 'Lebanon ',
 'Lesotho ',
 'Liberia ',
 'Libya ',
 'Lithuania ',
 'Macedonia, FYR  ',
 'Madagascar ',
 'Malawi ',
 'Malaysia ',
 'Maldives ',
 'Mali ',
 'Marshall Islands ',
 'Mauritania ',
 'Mauritius ',
 'Mayotte ',
 'Mexico ',
 'Micronesia, Fed. Sts. ',
 'Moldova ',
 'Mongolia ',
 'Montenegro ',
 'Morocco ',
 'Mozambique ',
 'Myanmar ',
 'Namibia ',
 'Nepal ',
 'Nicaragua ',
 'Niger ',
 'Nigeria  ',
 'Pakistan  ',
 'Palau ',
 'Panama ',
 'Papua New Guinea  ',
 'Paraguay ',
 'Peru  ',
 'Philippines ',
 'Romania ',
 'Russian Federation ',
 'Rwanda ',
 'Samoa ',
 'São Tomé and Principe ',
 'Senegal ',
 'Serbia ',
 'Seychelles ',
 'Sierra Leone ',
 'Solomon Islands ',
 'Somalia ',
 'South Africa ',
 'Sri Lanka ',
 'St. Kitts and Nevis ',
 'St. Lucia ',
 'St. Vincent and the Grenadines ',
 'Sudan ',
 'Suriname ',
 'Swaziland ',
 'Syrian Arab Republic ',
 'Tajikistan ',
 'Tanzania ',
 'Thailand ',
 'Timor-Leste ',
 'Togo ',
 'Tonga ',
 'Tunisia ',
 'Turkey ',
 'Turkmenistan ',
 'Tuvalu ',
 'Uganda ',
 'Ukraine ',
 'Uruguay ',
 'Uzbekistan ',
 'Vanuatu ',
 'Venezuela',
 'Vietnam ',
 'West Bank and Gaza ',
 'Yemen, Rep. ',
 'Zambia ',
 'Zimbabwe ']

In [208]:
real_name = []
for country_name in developing_country:
    real_name.append(country_name[:-1])

In [209]:
real_name

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Azerbaijan',
 'Bangladesh',
 'Belarus',
 'Belize ',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo, Dem. Rep',
 'Congo, Rep.',
 'Costa Rica',
 'Côte d’Ivoire',
 'Cuba',
 'Djibouti',
 'Dominica',
 'Dominican Republic ',
 'Ecuador',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Eritrea',
 'Ethiopia',
 'Fiji',
 'Gabon',
 'Gambia',
 'Georgia',
 'Ghana',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bisau',
 'Guyana',
 'Haiti',
 'Honduras',
 'India',
 'Indonesia',
 'Iran, Islamic Rep.',
 'Iraq',
 'Jamaica',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea, Dem Rep.',
 'Kosovo ',
 'Kyrgyz Republic',
 'Lao PDR',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Macedonia, FYR ',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia, Fed. Sts.',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Nicaragua',
 'Niger',
 'Nigeria ',
 'Pakistan ',
 'Palau',
 'Panama',
 'Papua New Guinea ',
 'Paraguay',
 'Peru ',
 'Philippines',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'São Tomé and Principe',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Vincent and the Grenadines',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuel',
 'Vietnam',
 'West Bank and Gaza',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe']

In [210]:
developing_country_co2 = co2_per_capitadf[co2_per_capitadf['Country Name'].isin(real_name)]

In [213]:
developing_country_co2

,Country Name,2014_x,2014_y,co2_per_capita
1,Afghanistan,9.809225e+03,3.275802e+07,0.000299
2,Angola,3.476316e+04,2.692047e+07,0.001291
3,Albania,5.716853e+03,2.889104e+06,0.001979
7,Argentina,2.040245e+05,4.298152e+07,0.004747
8,Armenia,5.529836e+03,2.906220e+06,0.001903
9,American Samoa,NaN,5.543700e+04,NaN
10,Antigua and Barbuda,5.317150e+02,9.887500e+04,0.005378
13,Azerbaijan,3.748774e+04,9.535079e+06,0.003932
14,Burundi,4.400400e+02,9.891790e+06,0.000044
16,Benin,6.318241e+03,1.028671e+07,0.000614
17,Burkina Faso,2.849259e+03,1.758598e+07,0.000162
18,Bangladesh,7.318965e+04,1.594053e+08,0.000459
19,Bulgaria,4.241619e+04,7.223938e+06,0.005872
22,Bosnia and Herzegovina,2.223302e+04,3.566002e+06,0.006235
23,Belarus,6.349777e+04,9.474511e+06,0.006702
26,Bolivia,2.041052e+04,1.056216e+07,0.001932
27,Brazil,5.298082e+05,2.042131e+08,0.002594
30,Bhutan,1.001091e+03,7.764480e+05,0.001289
31,Botswana,7.033306e+03,2.168573e+06,0.003243
32,Central African Republic,3.006940e+02,4.515392e+06,0.000067
37,Chile,8.256251e+04,1.761380e+07,0.004687
38,China,1.029193e+07,1.364270e+09,0.007544
40,Cameroon,7.003970e+03,2.223990e+07,0.000315
42,"Congo, Rep.",3.094948e+03,4.871101e+06,0.000635
43,Colombia,8.409164e+04,4.779191e+07,0.001760
44,Comoros,1.540140e+02,7.593850e+05,0.000203
46,Costa Rica,7.759372e+03,4.757575e+06,0.001631
48,Cuba,3.483650e+04,1.143977e+07,0.003045
54,Djibouti,7.223990e+02,9.121640e+05,0.000792
55,Dominica,1.356790e+02,7.277800e+04,0.001864
...,...,...,...,...
208,Sierra Leone,1.309119e+03,7.079162e+06,0.000185
209,El Salvador,6.285238e+03,6.281189e+06,0.001001
211,Somalia,6.087220e+02,1.351312e+07,0.000045
212,Serbia,3.766742e+04,7.130576e+06,0.005283
218,Suriname,1.991181e+03,5.479280e+05,0.003634
224,Seychelles,4.950450e+02,9.135900e+04,0.005419
225,Syrian Arab Republic,3.070379e+04,1.920309e+07,0.001599
227,Chad,7.297330e+02,1.356944e+07,0.000054
230,Togo,2.621905e+03,7.228915e+06,0.000363
231,Thailand,3.162127e+05,6.841677e+07,0.004622
232,Tajikistan,5.188805e+03,8.362745e+06,0.000620
233,Turkmenistan,6.842255e+04,5.466241e+06,0.012517
235,Timor-Leste,4.693760e+02,1.212814e+06,0.000387
237,Tonga,1.210110e+02,1.057820e+05,0.001144
241,Tunisia,2.882995e+04,1.114391e+07,0.002587
242,Turkey,3.459815e+05,7.703063e+07,0.004491
243,Tuvalu,1.100100e+01,1.090800e+04,0.001009
244,Tanzania,1.156205e+04,5.223487e+07,0.000221
245,Uganda,5.229142e+03,3.883334e+07,0.000135
246,Ukraine,2.272990e+05,4.527195e+07,0.005021
248,Uruguay,6.747280e+03,3.419546e+06,0.001973
250,Uzbekistan,1.052136e+05,3.075770e+07,0.003421
251,St. Vincent and the Grenadines,2.090190e+02,1.093570e+05,0.001911
255,Vietnam,1.669108e+05,9.254492e+07,0.001804
256,Vanuatu,1.540140e+02,2.588500e+05,0.000595
258,Samoa,1.980180e+02,1.922900e+05,0.001030
260,"Yemen, Rep.",2.269873e+04,2.624633e+07,0.000865
261,South Africa,4.897719e+05,5.453957e+07,0.008980
262,Zambia,4.503076e+03,1.562097e+07,0.000288
263,Zimbabwe,1.202043e+04,1.541168e+07,0.000780

In [366]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def check_link(url):
    try:

        r = requests.get(url)
        r.raise_for_status()
        r.encoding = r.apparent_encoding
        return r.text
    except:
        print('Connection Failed！！！')


def get_contents(ulist, rurl):
    soup = BeautifulSoup(rurl, 'lxml')
    trs = soup.find_all('tr')
    for tr in trs:
        ui = []
        for td in tr:
            ui.append(td.string)
        ulist.append(ui)
    del ulist[0:2]
    del ulist[-1]


def creat_df(urlist):
        country = []
        head = []
        for i in range(len(urlist)):
            country.append(urlist[i][2])
            head.append(urlist[i][4])
        df = pd.DataFrame.from_dict({"Country": country, "Head": head})
        return df

urli = []
url = "https://www.drovers.com/article/world-cattle-inventory-ranking-countries-fao"
rs = check_link(url)
get_contents(urli, rs)
Cattle = creat_df(urli)

vehicles_df_og = pd.read_csv('Motor vehicles per 1000 people.csv')
vehicles_df = vehicles_df_og.drop(columns='Date', axis=1)

df_Pop = datafile.loc[datafile['Indicator Code'] == "SP.POP.TOTL"].reset_index(drop=True)
df_Pop = df_Pop.loc[:, ['Country Name', '2014']]
df_Pop.columns = ['Country', 'Population']

df_Forest = datafile.loc[datafile['Indicator Code'] == "AG.LND.FRST.ZS"].reset_index(drop=True)
df_Forest = df_Forest.loc[:, ['Country_Name', '2014']]
df_Forest.columns = ['Country', 'Forest_Land_Percentage_of_all_land']

result1 = pd.merge(df_Pop, df_Forest, on='Country')
result = pd.merge(pd.merge(vehicles_df, Cattle, on='Country'), result1, on='Country')
result['Head'] = result['Head'].str.replace(',', '')
result['Head'] = result['Head'].astype('int')
result.eval('Heads_per_thousand_people = Head*1000/Population', inplace=True)
result = result.drop(columns=['Head', 'Population'], axis=1)
result = result.rename(columns={'Amount': 'Number_of_cars_per_thousand_people'})

ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat

In [331]:
result = result.rename(columns= {'Country': 'Country Name'})

In [332]:
result

,Country Name,Number_of_cars_per_thousand_people,Forest_Land_Percentage_of_all_land,Heads_per_thousand_people
0,United States,797,33.869659,280.267693
1,Liechtenstein,750,43.125001,161.876801
2,Iceland,745,0.477806,207.748651
3,Luxembourg,739,35.679011,348.043119
4,Australia,717,16.198664,1246.196266
5,New Zealand,712,38.554555,2257.826906
6,Malta,693,1.093750,35.024093
7,Italy,679,31.424492,100.207044
8,Guam,677,46.296296,0.869743
9,Puerto Rico,635,55.540024,107.500296
10,Greece,624,31.216447,62.336968
11,Finland,612,73.111981,166.958710
12,Canada,607,38.171794,343.742237
13,Spain,593,36.752045,122.564585
14,Japan,591,68.464998,31.938464
15,Norway,584,33.166905,165.455638
16,France,578,30.820536,287.951181
17,Austria,578,46.862087,228.824776
18,Germany,572,32.722843,155.428889
19,Slovenia,567,61.956308,223.117101
20,Switzerland,566,31.637816,190.900111
21,Lithuania,560,34.764565,248.672830
22,Belgium,559,22.554822,218.992909
23,Portugal,548,34.860315,141.427866
24,Bahrain,537,0.765240,7.856947
25,Poland,537,30.744962,154.150843
26,Qatar,532,0.000000,4.632712
27,Cyprus,532,18.693722,49.535324
28,Netherlands,528,11.142772,237.131225
29,Netherlands,528,11.142772,0.039727
...,...,...,...,...
120,Zambia,21,65.647374,257.772531
121,Pakistan,18,1.965286,206.412140
122,India,18,23.713117,146.074616
123,Cameroon,14,40.269933,261.030668
124,Gabon,14,88.485272,20.258963
125,Mali,14,3.928896,590.288092
126,Papua New Guinea,13,74.110764,11.991049
127,Equatorial Guinea,13,56.313725,4.692657
128,Burkina Faso,12,19.772660,506.797660
129,Mozambique,12,48.508861,62.104082
130,Haiti,12,3.548621,138.567483
131,Eritrea,11,14.994060,NaN
132,Malawi,8,33.570216,72.749182
133,Uganda,8,11.032316,335.278930
134,Tanzania,7,52.418153,469.641706
135,Niger,7,0.911344,532.686617
136,Sierra Leone,6,41.291215,81.648082
137,Chad,6,3.972046,574.821153
138,Burundi,6,10.568536,78.629449
139,Guinea,5,26.045906,423.531082
140,Rwanda,5,19.181192,99.796860
141,Nepal,5,25.364492,256.821668
142,Mauritania,5,0.221209,455.225497
143,Lesotho,4,1.581028,309.909893
144,Ethiopia,3,12.458400,554.603976
145,Liberia,3,43.698090,9.565592
146,Bangladesh,3,10.997926,150.559631
147,Solomon Islands,3,78.263669,26.064111
148,Somalia,3,10.265247,360.390361
149,Togo,2,3.820555,60.175006

In [330]:
co2_cattle_vehicle = pd.merge(result,developed_country_co2, on = 'Country Name')

In [322]:
co2_cattle_vehicle

,Country Name,Number_of_cars_per_thousand_people,Forest_Land_Percentage_of_all_land,Heads_per_thousand_people,2014_x,2014_y,co2_per_capita
0,United States,797,33.869659,280.267693,5254279.285,318622525.0,16490.608393
1,Iceland,745,0.477806,207.748651,1983.847,327386.0,6059.657407
2,Luxembourg,739,35.679011,348.043119,9658.878,556319.0,17362.121373
3,Australia,717,16.198664,1246.196266,361261.839,23504138.0,15370.137760
4,New Zealand,712,38.554555,2257.826906,34664.151,4509700.0,7686.575825
5,Italy,679,31.424492,100.207044,320411.459,60789140.0,5270.866786
6,Greece,624,31.216447,62.336968,67318.786,10892413.0,6180.337268
7,Finland,612,73.111981,166.958710,47300.633,5461512.0,8660.721243
8,Canada,607,38.171794,343.742237,537193.498,35535348.0,15117.158779
9,Spain,593,36.752045,122.564585,233976.602,46480882.0,5033.824487
10,Japan,591,68.464998,31.938464,1214048.358,127276000.0,9538.706103
11,Norway,584,33.166905,165.455638,47626.996,5137232.0,9270.945132
12,France,578,30.820536,287.951181,303275.568,66316092.0,4573.182147
13,Austria,578,46.862087,228.824776,58712.337,8546356.0,6869.867930
14,Germany,572,32.722843,155.428889,719883.438,80982500.0,8889.370395
15,Slovenia,567,61.956308,223.117101,12812.498,2061980.0,6213.686845
16,Switzerland,566,31.637816,190.900111,35305.876,8188649.0,4311.562994
17,Belgium,559,22.554822,218.992909,93350.819,11209057.0,8328.159898
18,Portugal,548,34.860315,141.427866,45052.762,10401062.0,4331.554028
19,Cyprus,532,18.693722,49.535324,6061.551,1152309.0,5260.352041
20,Netherlands,528,11.142772,237.131225,167303.208,16865008.0,9920.138075
21,Netherlands,528,11.142772,0.039727,167303.208,16865008.0,9920.138075
22,Sweden,520,68.922933,154.342927,43420.947,9696110.0,4478.182178
23,United Kingdom,519,12.925226,152.352864,419820.162,64613160.0,6497.440490
24,Ireland,513,10.862825,1481.963356,34066.430,4657740.0,7313.939808
25,Czech Republic,485,34.511785,128.529919,96475.103,10525347.0,9165.978376
26,Denmark,480,14.460109,286.108116,33498.045,5643475.0,5935.712482
27,Estonia,476,51.354955,198.852074,19519.441,1314545.0,14848.819173
28,Israel,346,7.523106,56.598951,64601.539,8215700.0,7863.181348
29,Singapore,149,23.060649,0.036565,56372.791,5469724.0,10306.331910
30,Turkey,144,15.088549,180.667409,345981.450,77030628.0,4491.479026

In [321]:
co2_cattle_vehicle['co2_per_capita'] = co2_cattle_vehicle['co2_per_capita'] * 1000000

In [282]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [303]:
model.fit(co2_cattle_vehicle[['Number_of_cars_per_thousand_people','Forest_Land_Percentage_of_all_land','Heads_per_thousand_people']], 
          co2_cattle_vehicle['co2_per_capita'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [304]:
model.intercept_

4342.7023803819

In [305]:
model.coef_

array([6.92328461, 2.83340294, 0.53244261])

In [307]:
co2_cattle_vehicle_cor = co2_cattle_vehicle[['Number_of_cars_per_thousand_people',
                                            'Forest_Land_Percentage_of_all_land',
                                            'Heads_per_thousand_people',
                                            'co2_per_capita']]

In [316]:
aaa = co2_cattle_vehicle_cor['Number_of_cars_per_thousand_people'].astype('int')

In [323]:
co2_cattle_vehicle_cor['Number_of_cars_per_thousand_people'] = aaa

/Users/sgarygao/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [364]:
type(result['Number_of_cars_per_thousand_people'][1])

str

In [385]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import lxml.html
import re
from sklearn.linear_model import LinearRegression

from time import sleep
from prettytable import PrettyTable

pd.options.display.max_columns = None

CO2_df = pd.read_csv('API_19_DS2_en_csv_v2_10515758.csv')
CO2_df.rename(columns={CO2_df.columns[0]: "Country_Name", CO2_df.columns[2]: "Indicator_Name", CO2_df.columns[3]:
    "Indicator_Code"}, inplace=True)

df_Arg_CO2 = CO2_df.loc[(CO2_df['Country_Name'] == "Argentina") & (CO2_df['Indicator_Code'] == "EN.ATM.CO2E.KT")].\
    reset_index(drop=True)
Arg_CO2 = df_Arg_CO2.loc[0, '1962':'2014']

df_Arg_Pop = CO2_df.loc[(CO2_df['Country_Name'] == "Argentina") & (CO2_df['Indicator_Code'] == "SP.POP.TOTL")].\
    reset_index(drop=True)
Arg_Pop = df_Arg_Pop.loc[0, '1962':'2014']

"""
GDP_df = pd.read_csv('API_NY.GDP.MKTP.CD_DS2_en_csv_v2_10515210.csv')
GDP_df.rename(columns={GDP_df.columns[0]: "Country_Name", GDP_df.columns[2]: "Indicator_Name", GDP_df.columns[3]:
    "Indicator_Code"}, inplace=True)
df_Arg_GDP = GDP_df.loc[(GDP_df['Country_Name'] == "Argentina")].reset_index(drop=True)
Arg_GDP = df_Arg_GDP.loc[0, '1962':'2014']
Arg_summary = pd.DataFrame({'A': Arg_GDP/Arg_Pop, 'B': Arg_CO2*1000/Arg_Pop})
# print(Arg_summary)

fig, ax = plt.subplots()
ax2 = ax.twinx()
Arg_summary.A.plot(ax=ax, style='b-')
Arg_summary.B.plot(ax=ax2, style='r-', secondary_y=True)

# plt.show()
"""

def check_link(url):
    try:

        r = requests.get(url)
        r.raise_for_status()
        r.encoding = r.apparent_encoding
        return r.text
    except:
        print('Connection Failed！！！')


def get_contents(ulist, rurl):
    soup = BeautifulSoup(rurl, 'lxml')
    trs = soup.find_all('tr')
    for tr in trs:
        ui = []
        for td in tr:
            ui.append(td.string)
        ulist.append(ui)
    del ulist[0:2]
    del ulist[-1]


def creat_df(urlist):
        country = []
        head = []
        for i in range(len(urlist)):
            country.append(urlist[i][2])
            head.append(urlist[i][4])
        df = pd.DataFrame.from_dict({"Country": country, "Head": head})
        return df

urli = []
url = "https://www.drovers.com/article/world-cattle-inventory-ranking-countries-fao"
rs = check_link(url)
get_contents(urli, rs)
Cattle = creat_df(urli)

vehicles_df_og = pd.read_csv('Motor vehicles per 1000 people.csv')
vehicles_df = vehicles_df_og.drop(columns='Date', axis=1)

df_Pop = CO2_df.loc[CO2_df['Indicator_Code'] == "SP.POP.TOTL"].reset_index(drop=True)
df_Pop = df_Pop.loc[:, ['Country_Name', '2014']]
df_Pop.columns = ['Country', 'Population']

df_Forest = CO2_df.loc[CO2_df['Indicator_Code'] == "AG.LND.FRST.ZS"].reset_index(drop=True)
df_Forest = df_Forest.loc[:, ['Country_Name', '2014']]
df_Forest.columns = ['Country', 'Forest_Land_Percentage_of_all_land']

result1 = pd.merge(df_Pop, df_Forest, on='Country')
result = pd.merge(pd.merge(vehicles_df, Cattle, on='Country'), result1, on='Country')
result['Head'] = result['Head'].str.replace(',', '')
result['Head'] = result['Head'].astype('int')
result['Amount'] = result['Amount'].astype('int')
result.eval('Heads_per_thousand_people = Head*1000/Population', inplace=True)
result = result.drop(columns=['Head', 'Population'], axis=1)
result = result.rename(columns={'Country':'Country_Name','Amount': 'Number_of_cars_per_thousand_people'})


co2_emission = CO2_df[CO2_df['Indicator_Code'] == 'EN.ATM.CO2E.KT']
co2_emission_2014 = co2_emission[['Country_Name','2014']]

population = CO2_df[CO2_df['Indicator_Code'] == 'SP.POP.TOTL']
population_2014 = population[['Country_Name','2014']]

co2_emission_2014 = co2_emission_2014.rename(columns={'2014':'2014_co2'})
population_2014 = population_2014.rename(columns= {'2014': '2014_pop'})
co2_per_thousand_df = pd.merge(co2_emission_2014, population_2014, on = 'Country_Name')


per_thousand_co2_em = (co2_per_thousand_df['2014_co2']/co2_per_thousand_df['2014_pop'])*1000000
co2_per_thousand_df['co2_per_thousand'] = per_thousand_co2_em

co2_per_thousand_df.dropna()


#developed countries:
developed_url = 'http://worldpopulationreview.com/countries/developed-countries/'
r = requests.get(developed_url)
tree = lxml.html.fromstring(r.content)
developed_country = tree.xpath('//li/a/text()')
developed_country = developed_country[8:]

#developing countries:
developing_url = 'https://isge2018.isgesociety.com/registration/list-of-developing-countries/'
r2 = requests.get(developing_url)
tree2 = lxml.html.fromstring(r2.content)
developing_country = tree2.xpath('//div/ul/li/text()')
developing_country = developing_country[4:]
real_name = []
for country_name in developing_country:
    real_name.append(country_name[:-1])



developed_country_co2 = co2_per_thousand_df[co2_per_thousand_df['Country_Name'].isin(developed_country)]

developing_country_co2 = co2_per_thousand_df[co2_per_thousand_df['Country_Name'].isin(real_name)]

developed_co2_cattle_vehicle_forest = pd.merge(result,developed_country_co2, on = 'Country_Name')


model = LinearRegression()
cor_matrix = developed_co2_cattle_vehicle_forest.corr()

model.fit(developed_co2_cattle_vehicle_forest[['Number_of_cars_per_thousand_people',
                                               'Forest_Land_Percentage_of_all_land',
                                               'Heads_per_thousand_people']],
          developed_co2_cattle_vehicle_forest['co2_per_thousand'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [375]:
cor_df = developed_co2_cattle_vehicle_forest[['co2_per_thousand',
                                              'Number_of_cars_per_thousand_people',
                                              'Forest_Land_Percentage_of_all_land',
                                              'Heads_per_thousand_people']]

In [376]:
cor_matrix1 = cor_df.corr()

In [377]:
cor_matrix1

,co2_per_thousand,Number_of_cars_per_thousand_people,Forest_Land_Percentage_of_all_land,Heads_per_thousand_people
co2_per_thousand,1.000000,0.282887,0.057406,0.141470
Number_of_cars_per_thousand_people,0.282887,1.000000,0.191402,0.290352
Forest_Land_Percentage_of_all_land,0.057406,0.191402,1.000000,-0.096330
Heads_per_thousand_people,0.141470,0.290352,-0.096330,1.000000

In [388]:
developing_co2_cattle_vehicle_forest = pd.merge(result,developing_country_co2, on = 'Country_Name')

In [389]:
cor_df2 = developing_co2_cattle_vehicle_forest[['co2_per_thousand',
                                              'Number_of_cars_per_thousand_people',
                                              'Forest_Land_Percentage_of_all_land',
                                              'Heads_per_thousand_people']]

In [393]:
cor_df2

,co2_per_thousand,Number_of_cars_per_thousand_people,Forest_Land_Percentage_of_all_land,Heads_per_thousand_people
0,4378.090123,560,34.764565,248.672830
1,4295.732552,434,13.413490,14.366588
2,5871.615869,393,35.057112,72.828975
3,6701.957705,362,42.437168,460.920886
4,8032.991579,361,67.511188,24.870371
5,3498.192882,319,53.965907,197.112824
6,4746.797455,314,10.015311,1188.766845
7,3556.071790,309,61.486989,136.216851
8,3634.019433,291,98.306409,84.062140
9,9186.845393,290,0.123328,31.994930
10,3866.241113,275,34.019189,260.844016
11,2594.388285,249,59.166513,1036.976853
12,5282.521917,238,31.083925,128.060342
13,3516.153691,235,29.519297,100.916024
14,14363.169742,219,1.225692,338.450402
15,4621.860032,206,32.040165,75.237706
16,1973.150822,200,10.411724,3363.019535
17,2593.215370,188,30.986148,59.397216
18,4687.376624,184,23.447812,187.657710
19,1320.574708,179,55.409963,352.221593
20,1630.951062,177,53.384255,273.248451
21,5418.677963,176,88.413039,3.283749
22,3353.110472,175,18.995075,5.551440
23,1143.965892,174,12.500000,110.604829
24,5020.747064,173,16.632775,102.622050
25,3002.514727,165,1.098220,7.843978
26,8980.119297,165,7.617737,256.694355
27,1864.285911,163,58.133331,192.365825
28,2411.541991,155,40.615915,302.870942
29,4491.479026,144,15.088549,180.667409
...,...,...,...,...
69,608.809117,22,43.177687,235.801858
70,614.213852,22,38.675062,205.702269
71,437.759998,21,54.296399,189.905041
72,288.271141,21,65.647374,257.772531
73,1730.000432,18,23.713117,146.074616
74,314.928068,14,40.269933,261.030668
75,2768.265721,14,88.485272,20.258963
76,83.228663,14,3.928896,590.288092
77,162.018806,12,19.772660,506.797660
78,309.666607,12,48.508861,62.104082
79,270.538586,12,3.548621,138.567483
80,NaN,11,14.994060,NaN
81,74.762910,8,33.570216,72.749182
82,134.656001,8,11.032316,335.278930
83,221.347372,7,52.418153,469.641706
84,111.073516,7,0.911344,532.686617
85,184.925702,6,41.291215,81.648082
86,53.777688,6,3.972046,574.821153
87,44.485376,6,10.568536,78.629449
88,207.492621,5,26.045906,423.531082
89,74.016446,5,19.181192,99.796860
90,283.538526,5,25.364492,256.821668
91,666.822428,5,0.221209,455.225497
92,1150.111032,4,1.581028,309.909893
93,119.124015,3,12.458400,554.603976
94,212.967664,3,43.698090,9.565592
95,459.141965,3,10.997926,150.559631
96,350.449345,3,78.263669,26.064111
97,45.046723,3,10.265247,360.390361
98,362.696892,2,3.820555,60.175006

In [391]:
cor_matrix2 = cor_df2.corr()

In [392]:
cor_matrix2

,co2_per_thousand,Number_of_cars_per_thousand_people,Forest_Land_Percentage_of_all_land,Heads_per_thousand_people
co2_per_thousand,1.000000,0.591719,-0.071004,-0.039683
Number_of_cars_per_thousand_people,0.591719,1.000000,0.164609,0.020437
Forest_Land_Percentage_of_all_land,-0.071004,0.164609,1.000000,-0.137975
Heads_per_thousand_people,-0.039683,0.020437,-0.137975,1.000000

In [394]:
model.coef_

array([6.92328461, 2.83340294, 0.53244261])

In [395]:
model.intercept_

4342.7023803819

In [400]:
developing_co2_cattle_vehicle_forest = developing_co2_cattle_vehicle_forest.dropna()

In [401]:
model2 = LinearRegression()

model2.fit(developing_co2_cattle_vehicle_forest[['Number_of_cars_per_thousand_people',
                                               'Forest_Land_Percentage_of_all_land',
                                               'Heads_per_thousand_people']],
          developing_co2_cattle_vehicle_forest['co2_per_thousand'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [402]:
model2.coef_

array([ 14.69583133, -20.73844965,  -0.47548491])

In [403]:
model2.intercept_

1592.2040268390526