In [52]:
import numpy as np
import pandas as pd
import requests
import lxml.html
import re
import urllib
from time import sleep
from prettytable import PrettyTable
from bs4 import BeautifulSoup

datafile = pd.read_csv("API_19_DS2_en_csv_v2_10515758.csv",sep = ',')

In [53]:
datafile

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,Urban population (% of total),SP.URB.TOTL.IN.ZS,50.776000,50.761000,50.746000,50.730000,50.715000,50.700000,...,4.342100e+01,4.305900e+01,4.294000e+01,4.295700e+01,4.299000e+01,4.304100e+01,4.310800e+01,43.192000,43.293000,NaN
1,Aruba,ABW,Urban population,SP.URB.TOTL,27526.000000,28141.000000,28532.000000,28761.000000,28924.000000,29082.000000,...,4.405200e+04,4.377800e+04,4.382200e+04,4.406400e+04,4.436000e+04,4.467400e+04,4.497900e+04,45275.000000,45572.000000,NaN
2,Aruba,ABW,Urban population growth (annual %),SP.URB.GROW,3.117931,2.209658,1.379868,0.799404,0.565140,0.544773,...,-7.305493e-01,-6.239346e-01,1.004566e-01,5.507148e-01,6.695040e-01,7.053514e-01,6.804037e-01,0.655929,0.653849,NaN
3,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.000000,55438.000000,56225.000000,56695.000000,57032.000000,57360.000000,...,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,104822.000000,105264.000000,NaN
4,Aruba,ABW,Population growth (annual %),SP.POP.GROW,3.148037,2.238144,1.409622,0.832453,0.592649,0.573468,...,9.861642e-02,2.126801e-01,3.769848e-01,5.121450e-01,5.929140e-01,5.874924e-01,5.246582e-01,0.459929,0.420781,NaN
5,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Aruba,ABW,"Prevalence of underweight, weight for age (% o...",SH.STA.MALN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aruba,ABW,"Community health workers (per 1,000 people)",SH.MED.CMHW.P3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Aruba,ABW,"Mortality rate, under-5 (per 1,000 live births)",SH.DYN.MORT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Aruba,ABW,"Primary completion rate, total (% of relevant ...",SE.PRM.CMPT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.624258e+01,9.478610e+01,NaN,NaN,9.657064e+01,1.011806e+02,NaN,NaN,NaN,NaN
10,Aruba,ABW,"School enrollment, primary and secondary (gros...",SE.ENR.PRSC.FM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.004440e+00,1.014600e+00,1.008710e+00,1.021560e+00,NaN,NaN,NaN,NaN,NaN,NaN
11,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.403979e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Aruba,ABW,CPIA public sector management and institutions...,IQ.CPA.PUBS.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Aruba,ABW,Ease of doing business index (1=most business-...,IC.BUS.EASE.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Aruba,ABW,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.527983,0.141163,NaN
15,Aruba,ABW,Marine protected areas (% of territorial waters),ER.MRN.PTMR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000105,NaN
16,Aruba,ABW,Terrestrial protected areas (% of total land a...,ER.LND.PTLD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.530000,18.917576,NaN
17,Aruba,ABW,"Annual freshwater withdrawals, total (% of int...",ER.H2O.FWTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Aruba,ABW,"Annual freshwater withdrawals, total (billion ...",ER.H2O.FWTL.K3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Aruba,ABW,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Aruba,ABW,Population living in areas where elevation is ...,EN.POP.EL5M.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.069167e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Aruba,ABW,Urban population living in areas where elevati...,EN.POP.EL5M.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.718044e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Aruba,ABW,Rural population living in areas where elevati...,EN.POP.EL5M.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.351123e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Aruba,ABW,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Aruba,ABW,GHG net emissions/removals by LUCF (Mt of CO2 ...,EN.CLC.GHGR.MT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Aruba,ABW,Disaster risk reduction progress score (1-5 sc...,EN.CLC.DRSK.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Aruba,ABW,SF6 gas emissions (thousand metric tons of CO2...,EN.ATM.SF6G.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Aruba,ABW,PFC gas emissions (thousand metric tons of CO2...,EN.ATM.PFCG.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Aruba,ABW,Nitrous oxide emissions (% change from 1990),EN.ATM.NOXE.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.821291e+01,-4.619562e+01,-4.565757e+01,-4.511953e+01,NaN,NaN,NaN,NaN,NaN,NaN
29,Aruba,ABW,Nitrous oxide emissions (thousand metric tons ...,EN.ATM.NOXE.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,6.123027e+00,6.361541e+00,6.425156e+00,6.488772e+00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20034,Zimbabwe,ZWE,CO2 emissions from gaseous fuel consumption (%...,EN.ATM.CO2E.GF.ZS,NaN,NaN,NaN,NaN,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
20035,Zimbabwe,ZWE,CO2 emissions from gaseous fuel consumption (kt),EN.ATM.CO2E.GF.KT,NaN,NaN,NaN,NaN,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
20036,Zimbabwe,ZWE,CO2 intensity (kg per kg of oil equivalent ene...,EN.ATM.CO2E.EG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.132464e-01,8.222593e-01,9.328746e-01,7.208452e-01,1.034544e+00,NaN,NaN,NaN,NaN,NaN
20037,Zimbabwe,ZWE,Energy use (kg of oil equivalent per capita),EG.USE.PCAP.KG.OE,NaN,NaN,NaN,NaN,NaN,NaN,...,6.615867e+02,6.714989e+02,7.125832e+02,7.348366e+02,7.496671e+02,NaN,NaN,NaN,NaN,NaN
20038,Zimbabwe,ZWE,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,5.310414e+02,5.468427e+02,5.702509e+02,5.427296e+02,5.575739e+02,5.369955e+02,NaN,NaN,NaN,NaN
20039,Zimbabwe,ZWE,"Energy use (kg of oil equivalent) per $1,000 G...",EG.USE.COMM.GD.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.466498e+02,3.863724e+02,3.667039e+02,3.314408e+02,3.392795e+02,NaN,NaN,NaN,NaN,NaN
20040,Zimbabwe,ZWE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.315371e+01,8.287954e+01,7.957423e+01,7.801970e+01,7.956109e+01,8.104929e+01,8.179781e+01,NaN,NaN,NaN
20041,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.817858e-01,1.084824e+00,1.421441e+00,1.825492e+00,1.734587e+00,1.436266e+00,1.328664e+00,NaN,NaN,NaN
20042,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,5.700000e+07,9.400000e+07,1.310000e+08,1.680000e+08,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN
20043,Zimbabwe,ZWE,Renewable electricity output (% of total elect...,EG.ELC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.564120e+01,6.800923e+01,5.785590e+01,6.039335e+01,5.393939e+01,5.560543e+01,5.272428e+01,NaN,NaN,NaN
20044,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.880263e-01,2.769763e-01,4.882812e-01,5.541671e-01,5.956113e-01,5.385996e-01,4.943867e-01,NaN,NaN,NaN
20045,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
20046,Zimbabwe,ZWE,Electricity production from natural gas source...,EG.ELC.NGAS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN
20047,Zimbabwe,ZWE,Electricity production from hydroelectric sour...,EG.ELC.HYRO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.485942e+01,6.692441e+01,5.643446e+01,5.856786e+01,5.220481e+01,5.416916e+01,5.139561e+01,NaN,NaN,NaN
20048,Zimbabwe,ZWE,Electricity production from coal sources (% of...,EG.ELC.COAL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.407077e+01,3.171379e+01,4.165582e+01,3.905248e+01,4.546499e+01,4.385597e+01,4.678134e+01,NaN,NaN,NaN
20049,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.336908e+01,3.606306e+01,3.690000e+01,3.672888e+01,3.707681e+01,3.230000e+01,3.370000e+01,38.145138,NaN,NaN
20050,Zimbabwe,ZWE,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.086305e+00,1.018022e+00,2.441511e+00,2.044131e+00,1.954060e+00,2.425173e+00,1.999687e+00,1.669274,1.121496,NaN
20051,Zimbabwe,ZWE,Cereal yield (kg per hectare),AG.YLD.CREL.KG,NaN,919.700000,905.900000,822.500000,820.500000,930.800000,...,4.523000e+02,7.337000e+02,5.876000e+02,6.960000e+02,6.697000e+02,8.363000e+02,5.586000e+02,580.000000,NaN,NaN
20052,Zimbabwe,ZWE,Average precipitation in depth (mm per year),AG.LND.PRCP.MM,NaN,NaN,657.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,6.570000e+02,NaN,6.570000e+02,NaN,NaN,NaN,NaN
20053,Zimbabwe,ZWE,Agricultural irrigated land (% of total agricu...,AG.LND.IRIG.AG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20054,Zimbabwe,ZWE,Forest area (% of land area),AG.LND.FRST.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.123304e+01,4.038775e+01,3.958020e+01,3.877265e+01,3.796510e+01,3.715756e+01,3.635001e+01,35.542457,NaN,NaN
20055,Zimbabwe,ZWE,Forest area (sq. km),AG.LND.FRST.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,1.595100e+05,1.562400e+05,1.531160e+05,1.499920e+05,1.468680e+05,1.437440e+05,1.406200e+05,137495.996100,NaN,NaN
20056,Zimbabwe,ZWE,Land area where elevation is below 5 meters (%...,AG.LND.EL5M.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20057,Zimbabwe,ZWE,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20058,Zimbabwe,ZWE,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20059,Zimbabwe,ZWE,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20060,Zimbabwe,ZWE,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20061,Zimbabwe,ZWE,Arable land (% of land area),AG.LND.ARBL.ZS,NaN,4.872690,5.001939,5.131188,5.260437,5.337986,...,1.059842e+01,1.033993e+01,1.085692e+01,1.033993e+01,1.033993e+01,1.033993e+01,1.033993e+01,10.339925,NaN,NaN
20062,Zimbabwe,ZWE,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,28.396019,28.615743,28.835466,29.055189,29.223213,...,4.213519e+01,4.187670e+01,4.239369e+01,4.187670e+01,4.187670e+01,4.187670e+01,4.187670e+01,41.876696,NaN,NaN
20063,Zimbabwe,ZWE,Agricultural land (sq. km),AG.LND.AGRI.K2,NaN,109850.000000,110700.000000,111550.000000,112400.000000,113050.000000,...,1.630000e+05,1.620000e+05,1.640000e+05,1.620000e+05,1.620000e+05,1.620000e+05,1.620000e+05,162000.000000,NaN,NaN

In [54]:
co2_emission = datafile[datafile['Indicator Code'] == 'EN.ATM.CO2E.KT']

In [55]:
co2_emission_2014 = co2_emission[['Country Name','2014']]

In [56]:
co2_emission_2014

                                            Country Name          2014
44                                                 Aruba  8.727460e+02
120                                          Afghanistan  9.809225e+03
196                                               Angola  3.476316e+04
272                                              Albania  5.716853e+03
348                                              Andorra  4.620420e+02
424                                           Arab World  1.895700e+06
500                                 United Arab Emirates  2.113695e+05
576                                            Argentina  2.040245e+05
652                                              Armenia  5.529836e+03
728                                       American Samoa           NaN
804                                  Antigua and Barbuda  5.317150e+02
880                                            Australia  3.612618e+05
956                                              Austria  5.871234e+04
1032                                          Azerbaijan  3.748774e+04
1108                                             Burundi  4.400400e+02
1184                                             Belgium  9.335082e+04
1260                                               Benin  6.318241e+03
1336                                        Burkina Faso  2.849259e+03
1412                                          Bangladesh  7.318965e+04
1488                                            Bulgaria  4.241619e+04
1564                                             Bahrain  3.133818e+04
1640                                        Bahamas, The  2.416553e+03
1716                              Bosnia and Herzegovina  2.223302e+04
1792                                             Belarus  6.349777e+04
1868                                              Belize  4.950450e+02
1944                                             Bermuda  5.757190e+02
2020                                             Bolivia  2.041052e+04
2096                                              Brazil  5.298082e+05
2172                                            Barbados  1.272449e+03
2248                                   Brunei Darussalam  9.108828e+03
...                                                  ...           ...
17828  Latin America & the Caribbean (IDA & IBRD coun...  1.844358e+06
17904                                        Timor-Leste  4.693760e+02
17980  Middle East & North Africa (IDA & IBRD countries)  1.415554e+06
18056                                              Tonga  1.210110e+02
18132                            South Asia (IDA & IBRD)  2.516435e+06
18208          Sub-Saharan Africa (IDA & IBRD countries)  8.228190e+05
18284                                Trinidad and Tobago  4.627387e+04
18360                                            Tunisia  2.882995e+04
18436                                             Turkey  3.459815e+05
18512                                             Tuvalu  1.100100e+01
18588                                           Tanzania  1.156205e+04
18664                                             Uganda  5.229142e+03
18740                                            Ukraine  2.272990e+05
18816                                Upper middle income  1.658879e+07
18892                                            Uruguay  6.747280e+03
18968                                      United States  5.254279e+06
19044                                         Uzbekistan  1.052136e+05
19120                     St. Vincent and the Grenadines  2.090190e+02
19196                                      Venezuela, RB  1.852202e+05
19272                             British Virgin Islands  1.796830e+02
19348                              Virgin Islands (U.S.)           NaN
19424                                            Vietnam  1.669108e+05
19500                                            Vanuatu  1.540140e+02
19576                                              World  3.613828e+07
19652                                              Samoa  1.980180e+02
19728                                             Kosovo           NaN
19804                                        Yemen, Rep.  2.269873e+04
19880                                       South Africa  4.897719e+05
19956                                             Zambia  4.503076e+03
20032                                           Zimbabwe  1.202043e+04

[264 rows x 2 columns]

In [15]:
co2_emission_2014.isnull().sum()

Country Name     0
2014            13
dtype: int64

In [57]:
population = datafile[datafile['Indicator Code'] == 'SP.POP.TOTL']

In [60]:
population_2014 = population[['Country Name','2014']]

In [61]:
population_2014

                                            Country Name          2014
3                                                  Aruba  1.037950e+05
79                                           Afghanistan  3.275802e+07
155                                               Angola  2.692047e+07
231                                              Albania  2.889104e+06
307                                              Andorra  7.922300e+04
383                                           Arab World  3.900430e+08
459                                 United Arab Emirates  9.070867e+06
535                                            Argentina  4.298152e+07
611                                              Armenia  2.906220e+06
687                                       American Samoa  5.543700e+04
763                                  Antigua and Barbuda  9.887500e+04
839                                            Australia  2.350414e+07
915                                              Austria  8.546356e+06
991                                           Azerbaijan  9.535079e+06
1067                                             Burundi  9.891790e+06
1143                                             Belgium  1.120906e+07
1219                                               Benin  1.028671e+07
1295                                        Burkina Faso  1.758598e+07
1371                                          Bangladesh  1.594053e+08
1447                                            Bulgaria  7.223938e+06
1523                                             Bahrain  1.336397e+06
1599                                        Bahamas, The  3.821690e+05
1675                              Bosnia and Herzegovina  3.566002e+06
1751                                             Belarus  9.474511e+06
1827                                              Belize  3.516940e+05
1903                                             Bermuda  6.513900e+04
1979                                             Bolivia  1.056216e+07
2055                                              Brazil  2.042131e+08
2131                                            Barbados  2.833850e+05
2207                                   Brunei Darussalam  4.117040e+05
...                                                  ...           ...
17787  Latin America & the Caribbean (IDA & IBRD coun...  6.081360e+08
17863                                        Timor-Leste  1.212814e+06
17939  Middle East & North Africa (IDA & IBRD countries)  3.567833e+08
18015                                              Tonga  1.057820e+05
18091                            South Asia (IDA & IBRD)  1.721848e+09
18167          Sub-Saharan Africa (IDA & IBRD countries)  9.790179e+08
18243                                Trinidad and Tobago  1.354493e+06
18319                                            Tunisia  1.114391e+07
18395                                             Turkey  7.703063e+07
18471                                             Tuvalu  1.090800e+04
18547                                           Tanzania  5.223487e+07
18623                                             Uganda  3.883334e+07
18699                                            Ukraine  4.527195e+07
18775                                Upper middle income  2.517980e+09
18851                                            Uruguay  3.419546e+06
18927                                      United States  3.186225e+08
19003                                         Uzbekistan  3.075770e+07
19079                     St. Vincent and the Grenadines  1.093570e+05
19155                                      Venezuela, RB  3.073838e+07
19231                             British Virgin Islands  2.958800e+04
19307                              Virgin Islands (U.S.)  1.078840e+05
19383                                            Vietnam  9.254492e+07
19459                                            Vanuatu  2.588500e+05
19535                                              World  7.271323e+09
19611                                              Samoa  1.922900e+05
19687                                             Kosovo  1.821800e+06
19763                                        Yemen, Rep.  2.624633e+07
19839                                       South Africa  5.453957e+07
19915                                             Zambia  1.562097e+07
19991                                           Zimbabwe  1.541168e+07

[264 rows x 2 columns]

In [65]:
co2_emission_2014.rename(columns={'2014':'2014_co2'})

                                            Country Name      2014_co2
44                                                 Aruba  8.727460e+02
120                                          Afghanistan  9.809225e+03
196                                               Angola  3.476316e+04
272                                              Albania  5.716853e+03
348                                              Andorra  4.620420e+02
424                                           Arab World  1.895700e+06
500                                 United Arab Emirates  2.113695e+05
576                                            Argentina  2.040245e+05
652                                              Armenia  5.529836e+03
728                                       American Samoa           NaN
804                                  Antigua and Barbuda  5.317150e+02
880                                            Australia  3.612618e+05
956                                              Austria  5.871234e+04
1032                                          Azerbaijan  3.748774e+04
1108                                             Burundi  4.400400e+02
1184                                             Belgium  9.335082e+04
1260                                               Benin  6.318241e+03
1336                                        Burkina Faso  2.849259e+03
1412                                          Bangladesh  7.318965e+04
1488                                            Bulgaria  4.241619e+04
1564                                             Bahrain  3.133818e+04
1640                                        Bahamas, The  2.416553e+03
1716                              Bosnia and Herzegovina  2.223302e+04
1792                                             Belarus  6.349777e+04
1868                                              Belize  4.950450e+02
1944                                             Bermuda  5.757190e+02
2020                                             Bolivia  2.041052e+04
2096                                              Brazil  5.298082e+05
2172                                            Barbados  1.272449e+03
2248                                   Brunei Darussalam  9.108828e+03
...                                                  ...           ...
17828  Latin America & the Caribbean (IDA & IBRD coun...  1.844358e+06
17904                                        Timor-Leste  4.693760e+02
17980  Middle East & North Africa (IDA & IBRD countries)  1.415554e+06
18056                                              Tonga  1.210110e+02
18132                            South Asia (IDA & IBRD)  2.516435e+06
18208          Sub-Saharan Africa (IDA & IBRD countries)  8.228190e+05
18284                                Trinidad and Tobago  4.627387e+04
18360                                            Tunisia  2.882995e+04
18436                                             Turkey  3.459815e+05
18512                                             Tuvalu  1.100100e+01
18588                                           Tanzania  1.156205e+04
18664                                             Uganda  5.229142e+03
18740                                            Ukraine  2.272990e+05
18816                                Upper middle income  1.658879e+07
18892                                            Uruguay  6.747280e+03
18968                                      United States  5.254279e+06
19044                                         Uzbekistan  1.052136e+05
19120                     St. Vincent and the Grenadines  2.090190e+02
19196                                      Venezuela, RB  1.852202e+05
19272                             British Virgin Islands  1.796830e+02
19348                              Virgin Islands (U.S.)           NaN
19424                                            Vietnam  1.669108e+05
19500                                            Vanuatu  1.540140e+02
19576                                              World  3.613828e+07
19652                                              Samoa  1.980180e+02
19728                                             Kosovo           NaN
19804                                        Yemen, Rep.  2.269873e+04
19880                                       South Africa  4.897719e+05
19956                                             Zambia  4.503076e+03
20032                                           Zimbabwe  1.202043e+04

[264 rows x 2 columns]

In [66]:
population_2014.rename(columns= {'2014': '2014_pop'})

                                            Country Name      2014_pop
3                                                  Aruba  1.037950e+05
79                                           Afghanistan  3.275802e+07
155                                               Angola  2.692047e+07
231                                              Albania  2.889104e+06
307                                              Andorra  7.922300e+04
383                                           Arab World  3.900430e+08
459                                 United Arab Emirates  9.070867e+06
535                                            Argentina  4.298152e+07
611                                              Armenia  2.906220e+06
687                                       American Samoa  5.543700e+04
763                                  Antigua and Barbuda  9.887500e+04
839                                            Australia  2.350414e+07
915                                              Austria  8.546356e+06
991                                           Azerbaijan  9.535079e+06
1067                                             Burundi  9.891790e+06
1143                                             Belgium  1.120906e+07
1219                                               Benin  1.028671e+07
1295                                        Burkina Faso  1.758598e+07
1371                                          Bangladesh  1.594053e+08
1447                                            Bulgaria  7.223938e+06
1523                                             Bahrain  1.336397e+06
1599                                        Bahamas, The  3.821690e+05
1675                              Bosnia and Herzegovina  3.566002e+06
1751                                             Belarus  9.474511e+06
1827                                              Belize  3.516940e+05
1903                                             Bermuda  6.513900e+04
1979                                             Bolivia  1.056216e+07
2055                                              Brazil  2.042131e+08
2131                                            Barbados  2.833850e+05
2207                                   Brunei Darussalam  4.117040e+05
...                                                  ...           ...
17787  Latin America & the Caribbean (IDA & IBRD coun...  6.081360e+08
17863                                        Timor-Leste  1.212814e+06
17939  Middle East & North Africa (IDA & IBRD countries)  3.567833e+08
18015                                              Tonga  1.057820e+05
18091                            South Asia (IDA & IBRD)  1.721848e+09
18167          Sub-Saharan Africa (IDA & IBRD countries)  9.790179e+08
18243                                Trinidad and Tobago  1.354493e+06
18319                                            Tunisia  1.114391e+07
18395                                             Turkey  7.703063e+07
18471                                             Tuvalu  1.090800e+04
18547                                           Tanzania  5.223487e+07
18623                                             Uganda  3.883334e+07
18699                                            Ukraine  4.527195e+07
18775                                Upper middle income  2.517980e+09
18851                                            Uruguay  3.419546e+06
18927                                      United States  3.186225e+08
19003                                         Uzbekistan  3.075770e+07
19079                     St. Vincent and the Grenadines  1.093570e+05
19155                                      Venezuela, RB  3.073838e+07
19231                             British Virgin Islands  2.958800e+04
19307                              Virgin Islands (U.S.)  1.078840e+05
19383                                            Vietnam  9.254492e+07
19459                                            Vanuatu  2.588500e+05
19535                                              World  7.271323e+09
19611                                              Samoa  1.922900e+05
19687                                             Kosovo  1.821800e+06
19763                                        Yemen, Rep.  2.624633e+07
19839                                       South Africa  5.453957e+07
19915                                             Zambia  1.562097e+07
19991                                           Zimbabwe  1.541168e+07

[264 rows x 2 columns]

In [127]:
co2_per_capitadf = pd.merge(co2_emission_2014, population_2014, on = 'Country Name')

In [128]:
co2_per_capitadf

,Country Name,2014_x,2014_y
0,Aruba,8.727460e+02,1.037950e+05
1,Afghanistan,9.809225e+03,3.275802e+07
2,Angola,3.476316e+04,2.692047e+07
3,Albania,5.716853e+03,2.889104e+06
4,Andorra,4.620420e+02,7.922300e+04
5,Arab World,1.895700e+06,3.900430e+08
6,United Arab Emirates,2.113695e+05,9.070867e+06
7,Argentina,2.040245e+05,4.298152e+07
8,Armenia,5.529836e+03,2.906220e+06
9,American Samoa,NaN,5.543700e+04
10,Antigua and Barbuda,5.317150e+02,9.887500e+04
11,Australia,3.612618e+05,2.350414e+07
12,Austria,5.871234e+04,8.546356e+06
13,Azerbaijan,3.748774e+04,9.535079e+06
14,Burundi,4.400400e+02,9.891790e+06
15,Belgium,9.335082e+04,1.120906e+07
16,Benin,6.318241e+03,1.028671e+07
17,Burkina Faso,2.849259e+03,1.758598e+07
18,Bangladesh,7.318965e+04,1.594053e+08
19,Bulgaria,4.241619e+04,7.223938e+06
20,Bahrain,3.133818e+04,1.336397e+06
21,"Bahamas, The",2.416553e+03,3.821690e+05
22,Bosnia and Herzegovina,2.223302e+04,3.566002e+06
23,Belarus,6.349777e+04,9.474511e+06
24,Belize,4.950450e+02,3.516940e+05
25,Bermuda,5.757190e+02,6.513900e+04
26,Bolivia,2.041052e+04,1.056216e+07
27,Brazil,5.298082e+05,2.042131e+08
28,Barbados,1.272449e+03,2.833850e+05
29,Brunei Darussalam,9.108828e+03,4.117040e+05
...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,1.844358e+06,6.081360e+08
235,Timor-Leste,4.693760e+02,1.212814e+06
236,Middle East & North Africa (IDA & IBRD countries),1.415554e+06,3.567833e+08
237,Tonga,1.210110e+02,1.057820e+05
238,South Asia (IDA & IBRD),2.516435e+06,1.721848e+09
239,Sub-Saharan Africa (IDA & IBRD countries),8.228190e+05,9.790179e+08
240,Trinidad and Tobago,4.627387e+04,1.354493e+06
241,Tunisia,2.882995e+04,1.114391e+07
242,Turkey,3.459815e+05,7.703063e+07
243,Tuvalu,1.100100e+01,1.090800e+04
244,Tanzania,1.156205e+04,5.223487e+07
245,Uganda,5.229142e+03,3.883334e+07
246,Ukraine,2.272990e+05,4.527195e+07
247,Upper middle income,1.658879e+07,2.517980e+09
248,Uruguay,6.747280e+03,3.419546e+06
249,United States,5.254279e+06,3.186225e+08
250,Uzbekistan,1.052136e+05,3.075770e+07
251,St. Vincent and the Grenadines,2.090190e+02,1.093570e+05
252,"Venezuela, RB",1.852202e+05,3.073838e+07
253,British Virgin Islands,1.796830e+02,2.958800e+04
254,Virgin Islands (U.S.),NaN,1.078840e+05
255,Vietnam,1.669108e+05,9.254492e+07
256,Vanuatu,1.540140e+02,2.588500e+05
257,World,3.613828e+07,7.271323e+09
258,Samoa,1.980180e+02,1.922900e+05
259,Kosovo,NaN,1.821800e+06
260,"Yemen, Rep.",2.269873e+04,2.624633e+07
261,South Africa,4.897719e+05,5.453957e+07
262,Zambia,4.503076e+03,1.562097e+07
263,Zimbabwe,1.202043e+04,1.541168e+07

In [72]:
per_capita_co2_em = co2_per_capitadf['2014_x']/co2_per_capitadf['2014_y']

In [136]:
co2_per_capitadf['co2_per_capita'] = per_capita_co2_em

In [137]:
co2_per_capitadf.dropna()

,Country Name,2014_x,2014_y,co2_per_capita
0,Aruba,8.727460e+02,1.037950e+05,0.008408
1,Afghanistan,9.809225e+03,3.275802e+07,0.000299
2,Angola,3.476316e+04,2.692047e+07,0.001291
3,Albania,5.716853e+03,2.889104e+06,0.001979
4,Andorra,4.620420e+02,7.922300e+04,0.005832
5,Arab World,1.895700e+06,3.900430e+08,0.004860
6,United Arab Emirates,2.113695e+05,9.070867e+06,0.023302
7,Argentina,2.040245e+05,4.298152e+07,0.004747
8,Armenia,5.529836e+03,2.906220e+06,0.001903
10,Antigua and Barbuda,5.317150e+02,9.887500e+04,0.005378
11,Australia,3.612618e+05,2.350414e+07,0.015370
12,Austria,5.871234e+04,8.546356e+06,0.006870
13,Azerbaijan,3.748774e+04,9.535079e+06,0.003932
14,Burundi,4.400400e+02,9.891790e+06,0.000044
15,Belgium,9.335082e+04,1.120906e+07,0.008328
16,Benin,6.318241e+03,1.028671e+07,0.000614
17,Burkina Faso,2.849259e+03,1.758598e+07,0.000162
18,Bangladesh,7.318965e+04,1.594053e+08,0.000459
19,Bulgaria,4.241619e+04,7.223938e+06,0.005872
20,Bahrain,3.133818e+04,1.336397e+06,0.023450
21,"Bahamas, The",2.416553e+03,3.821690e+05,0.006323
22,Bosnia and Herzegovina,2.223302e+04,3.566002e+06,0.006235
23,Belarus,6.349777e+04,9.474511e+06,0.006702
24,Belize,4.950450e+02,3.516940e+05,0.001408
25,Bermuda,5.757190e+02,6.513900e+04,0.008838
26,Bolivia,2.041052e+04,1.056216e+07,0.001932
27,Brazil,5.298082e+05,2.042131e+08,0.002594
28,Barbados,1.272449e+03,2.833850e+05,0.004490
29,Brunei Darussalam,9.108828e+03,4.117040e+05,0.022125
30,Bhutan,1.001091e+03,7.764480e+05,0.001289
...,...,...,...,...
232,Tajikistan,5.188805e+03,8.362745e+06,0.000620
233,Turkmenistan,6.842255e+04,5.466241e+06,0.012517
234,Latin America & the Caribbean (IDA & IBRD coun...,1.844358e+06,6.081360e+08,0.003033
235,Timor-Leste,4.693760e+02,1.212814e+06,0.000387
236,Middle East & North Africa (IDA & IBRD countries),1.415554e+06,3.567833e+08,0.003968
237,Tonga,1.210110e+02,1.057820e+05,0.001144
238,South Asia (IDA & IBRD),2.516435e+06,1.721848e+09,0.001461
239,Sub-Saharan Africa (IDA & IBRD countries),8.228190e+05,9.790179e+08,0.000840
240,Trinidad and Tobago,4.627387e+04,1.354493e+06,0.034163
241,Tunisia,2.882995e+04,1.114391e+07,0.002587
242,Turkey,3.459815e+05,7.703063e+07,0.004491
243,Tuvalu,1.100100e+01,1.090800e+04,0.001009
244,Tanzania,1.156205e+04,5.223487e+07,0.000221
245,Uganda,5.229142e+03,3.883334e+07,0.000135
246,Ukraine,2.272990e+05,4.527195e+07,0.005021
247,Upper middle income,1.658879e+07,2.517980e+09,0.006588
248,Uruguay,6.747280e+03,3.419546e+06,0.001973
249,United States,5.254279e+06,3.186225e+08,0.016491
250,Uzbekistan,1.052136e+05,3.075770e+07,0.003421
251,St. Vincent and the Grenadines,2.090190e+02,1.093570e+05,0.001911
252,"Venezuela, RB",1.852202e+05,3.073838e+07,0.006026
253,British Virgin Islands,1.796830e+02,2.958800e+04,0.006073
255,Vietnam,1.669108e+05,9.254492e+07,0.001804
256,Vanuatu,1.540140e+02,2.588500e+05,0.000595
257,World,3.613828e+07,7.271323e+09,0.004970
258,Samoa,1.980180e+02,1.922900e+05,0.001030
260,"Yemen, Rep.",2.269873e+04,2.624633e+07,0.000865
261,South Africa,4.897719e+05,5.453957e+07,0.008980
262,Zambia,4.503076e+03,1.562097e+07,0.000288
263,Zimbabwe,1.202043e+04,1.541168e+07,0.000780

In [80]:
developed_url = 'http://worldpopulationreview.com/countries/developed-countries/'

In [87]:
r = requests.get(developed_url)
tree = lxml.html.fromstring(r.content)

In [102]:
tree

In [153]:
developed_country = tree.xpath('//li/a/text()')

In [154]:
developed_country = developed_country[8:]

In [160]:
len(developed_country)

31

In [155]:
developed_country

['Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Iceland',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Luxembourg',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Portugal',
 'Slovenia',
 'South Korea',
 'Spain',
 'Sweden',
 'Singapore',
 'Switzerland',
 'Turkey',
 'United Kingdom',
 'United States']

In [95]:
developing_url = 'https://isge2018.isgesociety.com/registration/list-of-developing-countries/'

In [96]:
r2 = requests.get(developing_url)
tree2 = lxml.html.fromstring(r2.content)

In [101]:
tree2

In [103]:
developing_country = tree2.xpath('//div/ul/li/text()')

In [118]:
developing_country = developing_country[4:]

In [156]:
developed_country_co2 = co2_per_capitadf[co2_per_capitadf['Country Name'].isin(developed_country)]

In [157]:
developed_country_co2

       Country Name       2014_x       2014_y  co2_per_capita
11        Australia   361261.839   23504138.0        0.015370
12          Austria    58712.337    8546356.0        0.006870
15          Belgium    93350.819   11209057.0        0.008328
33           Canada   537193.498   35535348.0        0.015117
35      Switzerland    35305.876    8188649.0        0.004312
51           Cyprus     6061.551    1152309.0        0.005260
52   Czech Republic    96475.103   10525347.0        0.009166
53          Germany   719883.438   80982500.0        0.008889
56          Denmark    33498.045    5643475.0        0.005936
68            Spain   233976.602   46480882.0        0.005034
69          Estonia    19519.441    1314545.0        0.014849
73          Finland    47300.633    5461512.0        0.008661
75           France   303275.568   66316092.0        0.004573
79   United Kingdom   419820.162   64613160.0        0.006497
87           Greece    67318.786   10892413.0        0.006180
109         Ireland    34066.430    4657740.0        0.007314
112         Iceland     1983.847     327386.0        0.006060
113          Israel    64601.539    8215700.0        0.007863
114           Italy   320411.459   60789140.0        0.005271
117           Japan  1214048.358  127276000.0        0.009539
142      Luxembourg     9658.878     556319.0        0.017362
174     Netherlands   167303.208   16865008.0        0.009920
175          Norway    47626.996    5137232.0        0.009271
178     New Zealand    34664.151    4509700.0        0.007687
192        Portugal    45052.762   10401062.0        0.004332
206       Singapore    56372.791    5469724.0        0.010306
220        Slovenia    12812.498    2061980.0        0.006214
221          Sweden    43420.947    9696110.0        0.004478
242          Turkey   345981.450   77030628.0        0.004491
249   United States  5254279.285  318622525.0        0.016491

In [172]:
developed_country_co2['Country Name']

11          Australia
12            Austria
15            Belgium
33             Canada
35        Switzerland
51             Cyprus
52     Czech Republic
53            Germany
56            Denmark
68              Spain
69            Estonia
73            Finland
75             France
79     United Kingdom
87             Greece
109           Ireland
112           Iceland
113            Israel
114             Italy
117             Japan
142        Luxembourg
174       Netherlands
175            Norway
178       New Zealand
192          Portugal
206         Singapore
220          Slovenia
221            Sweden
242            Turkey
249     United States
Name: Country Name, dtype: object

In [164]:
len(developed_country_co2)

30

In [176]:
len(developed_country)

31

In [190]:
developed_country_co2_list =  list(developed_country_co2['Country Name'])

In [192]:
developed_country_co2_list

['Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Switzerland',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Denmark',
 'Spain',
 'Estonia',
 'Finland',
 'France',
 'United Kingdom',
 'Greece',
 'Ireland',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Luxembourg',
 'Netherlands',
 'Norway',
 'New Zealand',
 'Portugal',
 'Singapore',
 'Slovenia',
 'Sweden',
 'Turkey',
 'United States']

In [193]:
for i in range(0,30):
    if developed_country[i] not in developed_country_co2_list:
        missing_country = developed_country[i]

In [194]:
missing_country

'South Korea'

In [177]:
co2_per_capitadf[co2_per_capitadf['Country Name'] == 'South Korea']

Empty DataFrame
Columns: [Country Name, 2014_x, 2014_y, co2_per_capita]
Index: []